### ISSUE TITLE
vg2svg reading for STDIN broken

### ISSUE THREAD

**Issue by 8** [vega/vega#1276] opened 2018-05-18 10:49 UTC
Expectation:
vg2svg is able to read from STDIN.

Problem:
vg2svg is unable to read form STDIN, instead it tries to open a file named C:\dev\stdin

Additional Info:
If a source file is supplied using a parameter, vg2svg works.
So using a temp. file is working:
```
vl2vg vl.json 2>nul > vg.json
 vg2svg vg.json
```
But directly piping does not work:
```
vl2vg vl.json 2>nul | vg2svg
C:\Users\username\AppData\Roaming\npm\node_modules\vega\bin\vg2svg:56
  if (err) throw err;
           ^

Error: ENOENT: no such file or directory, open 'C:\dev\stdin'
```

Guesstimation:
Platform specific code used in:
```
    specFile = args._[0] || '/dev/stdin',
```
https://github.com/vega/vega/blob/337cdffae64694a8cde290dd61edf682747be6c2/bin/vg2svg#L51
instead of proper api:
https://nodejs.org/api/process.html#process_process_stdin

Take care,
Martin

**Comment by jheer** [comment] 2018-05-18 17:08
Thank you for the thorough report! Will fix for the next release.

**Comment by jheer** [comment] 2018-05-25 04:27
Fixed and released in v4.0.0-rc.2

**Closed by jheer** 2018-05-25 04:27 UTC
Labels: bug

**Comment by crouthamela** [comment] 2019-03-13 16:47
Hi there, I'm experiencing this same issue. I have vega-cli 5.2.0 installed via npm, with vega-lite 3.0.0-rc15. When I attempt this, I receive:

`ERROR: Failed to generate image: vl2vg.CMD failed: C:\Users\andrew\AppData\Roaming\npm\node_modules\vega-lite\bin\vl2vg:35
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'H:\dev\stdin'`

**Comment by jheer** [comment] 2019-03-13 18:08
Hi @crouthamela, thanks for posting! It looks like you are reporting issues with vl2vg in Vega-Lite. If you have a reproduction example using vg2svg directly, please share that in a new issue on this repo. (It also looks like you are using Windows; I don't know if that might be related to the error.)

If the issue is specific to vl2vg, please post an issue over at https://github.com/vega/vega-lite.
