### ISSUE TITLE
Canvas picking fails for clipped group with corner radius and no fill.

### ISSUE THREAD

**Issue by TaridaGeorge** [vega/vega#2797] opened 2020-08-12 11:23 UTC
Open a new editor at https://vega.github.io/editor/ paste this spec:

```
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 200,
  "height": 60,
  "marks": [
        {
          "name": "banddd",
          "type": "group",
          "encode": {
            "enter": {
              "stroke": {"value": "#2B303A"},
              "width": {"signal": "width"},
              "height": {"value": 40},
              "y": {"value": 10},
              "cornerRadius": {"value": 10},
              "strokeWidth": {"value": 2},
              "strokeForeground": {"value": true},
              "clip": {"value": true}
            }
          },
          "marks": [
            {
              "type": "rect",
              "encode": {
                "enter": {"tooltip": {"value": "hello"}},
                "update": {
                  "x": {"value": 0},
                  "y": {"value": 1},
                  "height": {"value": 38},
                  "width": {"value": 20},
                  "fill": {"value": "blue"}
                }
              }
            }
          ]
        }
      ]
}
```

hover over blue rectangle. No tooltip is present. Change clip property to false - hover the blue rectangle - tooltip is present.

Is this a bug or is the wanted behavior?

**Comment by domoritz** [comment] 2020-08-12 20:16
I cannot reproduce the issue. I see a tooltip. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aAEwAGNTPg0yWNADZNIZACcA1hDQBtUOKQI4aEEyTiF76SEwBPHI-RkJmwMOJ5w4lBsCv6g4ZhwJmigEJhBZjEgxEgANgz+IADEKgBCAMxqpQCCIAC+MvJKMEkgEDp22U4NynUYcDp6qKBZuf4ALGo93s3DeWgAjBMykSbiCQBKSAo0DJaDmTmzqAs9KWlwAOqKynsz-ionqWzpAGJsJuRBDG7TB-6peT0oNkaKEbr80P84DVoTJTBZrKAfH4nO8oJgwhEohk4glmpg2GxspgQT8Rk54Nlsmxaj0QgokPFmgAPUmHRYgKZgslHHraXTormHUoADh6XSagru7IAZjRKaz8kwydDoQBdGrqoA)

<img width="949" alt="Screen Shot 2020-08-12 at 13 15 38" src="https://user-images.githubusercontent.com/589034/90063241-ec42d300-dc9d-11ea-89d8-596c92f188c9.png">

**Comment by TaridaGeorge** [comment] 2020-08-12 20:41
Sometimes I get it to work too but sometimes I don't. Watch this video:

https://drive.google.com/file/d/1px61MOAmjg4Ys6WnwIpCDxSuV4SjIKSQ/view?usp=sharing

**Comment by domoritz** [comment] 2020-08-12 21:23
Oh strange. I am not seeing this issue in chrome 85.0.4183.59 on macOS. If it's inconsistent, I think there may be an issue with the browser and not Vega.

If you don't mind, I will close this issue here but you can keep commenting on it and maybe someone else sees a similar issue and will comment here as well.

**Comment by jheer** [comment] 2020-08-13 08:49
I can reproduce the error with the Canvas renderer. I've also tracked the bug down to how we are doing picking in the face of clipped groups with rounded corners. I have a fix to include in the next release, but in the meantime setting the background fill color of the group (e.g., `"fill": {"value": "transparent"}`) will fix the behavior of the current example.

**Closed** 2020-08-13 09:03 UTC
Labels: bug
