### ISSUE TITLE
The axis for timelines example looks wrong

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1283] opened 2018-05-20 05:38 UTC
https://vega.github.io/vega/examples/timelines/

![image](https://user-images.githubusercontent.com/111269/40276072-4e98e75e-5bb5-11e8-95fa-b335dfeb5545.png)

Why are they all ":00"?

**Comment by jheer** [comment] 2018-05-20 19:44
Are you seeing this on the live website? (I’m not.) This example is also included in our (passing) test suite. What platform / browser / version are you seeing this on?

**Comment by domoritz** [comment] 2018-05-20 19:53
I can confirm that I see the same chart as above on MacOS with Chrome 67.

**Comment by coenhallie** [comment] 2018-05-20 19:59
I use MacOS 10.13.4 and Chrome 66/ Firefox and see the correct dates.

,Coen

**Comment by domoritz** [comment] 2018-05-20 20:02
Firefox 61 is also correct over here.

<img width="575" alt="screen shot 2018-05-20 at 13 01 36" src="https://user-images.githubusercontent.com/589034/40283106-fb0f257a-5c2d-11e8-9be7-e9cfe24987e8.png">

Does this example use web audio :-P

**Comment by kenklin** [comment] 2018-05-20 20:10
Here are the results on My Mac Version 10.13.4 ...

CORRECT
Chrome: Version 66.0.3359.181 (Official Build) (64-bit)
Safari: Version 11.1 (13605.1.33.1.4)
Firefox: 59.0.2

BROKEN (:00 as above)
**Chrome Canary: Version 68.0.3416.0 (Official Build) canary (64-bit)**

**Comment by jheer** [comment] 2018-06-12 17:45
This issue has been addressed by adding an explicit `"%Y"` year format to the axis. However, the underlying bug appears to be due to changes to historical timezone offsets released in Chrome but not (yet?) in other browsers. This change is causing errors in d3-time, which then propagate to the axis formatting. To track the underlying issue, follow https://github.com/d3/d3-time/issues/29.

Related to vega/vega#1314 from @jwoLondon

**Closed by jheer** 2018-06-12 17:45 UTC
