### ISSUE TITLE
contour transform breaks on some inputs

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1149] opened 2018-02-13 03:40 UTC
Contour transformation results in a all-black visualization in two cases:

* Empty input -- to reproduce, use [contour example](https://vega.github.io/editor/#/examples/vega/contour-plot), and change `source`'s filter from `"datum['Horsepower'] != null && datum['Miles_per_Gallon'] != null"` to `"false"`. The whole graph will go black. Note that the resulting dataset is huge (`JSON.stringify(VEGA_DEBUG.view.data('contours')).length` in console gives 56481).  Empty resultset is expected.

* All points are outside of the screen's projection.  Repro:  change original contour example -- set `"autosize": "none"`, and set domain for "x" scale to manual `"domain": [2000,3000],`

P.S. A workaround solution to both of the listed problems is to add a `{"type": "filter", "expr": "datum.value != 0"}` filter right after the `contour` transform, but this seems very hacky.

**Comment by jheer** [comment] 2018-02-13 03:47
The contour result is what d3-contour generates given an empty data set. In Vega we could check for empty data and avoid generating any contours in this case. If you like, you might also file an issue on the d3-contour repo requesting that either no contours (or at minimum contours clipped to the provided size) be generated in response to empty data.

The all black visualization is due to a degenerate color encoding caused by a singular data domain with zero span.

**Comment by nyurik** [comment] 2018-02-13 04:04
Thanks @jheer , filed a task there.   The empty dataset handling in Vega would solve only the first problem. I guess the only way for the end user to handle this is to analyze the `value` field of the contour results, and if the domain min=max=0, avoid visualization.  I really wish there was some sort of a "disabled" expression on marks, allowing to easily avoid rendering of an object. I will file it as a feature request. Thanks for explanation!

**Comment by nyurik** [comment] 2018-02-13 04:24
@jheer would it make sense to add an automatic filter after contour transform, which will check if `min == max == 0` for the `value` field, and if so, simply return an empty resultset?  Is there ever a valid resultset that would match this condition?

**Comment by jheer** [comment] 2018-02-13 05:28
I've already made (but not yet pushed) updates that suppress any contours from being generated with an empty set of input values. This prevents the large degenerate contour from ever being generated and so gracefully degrades when the input data is empty. Will be included in the 3.1 release.

**Comment by nyurik** [comment] 2018-02-13 05:29
@jheer but this would only handle empty data sets, whereas I ran into the same issue when all the data is outside of the projected/scaled area. Would it make sense to handle both cases like this?

**Comment by jheer** [comment] 2018-02-13 06:12
No. In that case the contours are as specified. You should filter out data that you do not want included in the contour determination.

**Comment by jheer** [comment] 2018-02-19 21:12
Fixed in Vega 3.1 -- empty data is now handled to prevent any contours from being generated.

**Closed by jheer** 2018-02-19 21:12 UTC
