### ISSUE TITLE
candlestick example is broken on Firefox, but not Chrome

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1177] opened 2018-03-04 23:04 UTC
In the Friefox 58.0.2 (64-bit) on Ubuntu 17.10,  [VL candlestick example](https://vega.github.io/vega-lite/examples/layer_candlestick.html) is broken - both `data_1` and `data_2` has no data after filtering.

![image](https://user-images.githubusercontent.com/1641515/36951614-b08e2ffa-1fba-11e8-9d62-389e13a73330.png)
 
Originally filed as https://github.com/vega/vega-lite/issues/3457

**Comment by domoritz** [comment] 2018-03-05 00:35
The issue is most likely date parsing and thus should be fixed in the example.

**Closed by domoritz** 2018-03-05 00:35 UTC
