### ISSUE TITLE
Installation issues on Mac OS 10.9.5

### ISSUE THREAD

**Issue by aaelony** [vega/vega#391] opened 2015-10-20 19:16 UTC
Hello,

I followed the installation instructions but they cause an error and do not build properly. Either the instructions are incomplete with respect to a needed dependency or I have made some other mistake.  Could you please take a look?  

```

Issues installing Vega on Mac OS X 10.9.5



[2015-10-20 12:00:21] ~/p/vega $  npm --version
2.12.1
[2015-10-20 12:04:07] ~/p/vega $  node --version
v0.12.7
[2015-10-20 12:05:32] ~/p $  mkdir failed-attempt
[2015-10-20 12:05:50] ~/p $  cd failed-attempt/
[2015-10-20 12:05:52] ~/p/failed-attempt $  git clone https://github.com/vega/vega.git
Cloning into 'vega'...
remote: Counting objects: 10463, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 10463 (delta 18), reused 0 (delta 0), pack-reused 10423
Receiving objects: 100% (10463/10463), 30.27 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (7252/7252), done.
Checking connectivity... done.
[2015-10-20 12:06:26] ~/p/failed-attempt $  cd vega/
[2015-10-20 12:06:28] ~/p/failed-attempt/vega $  npm install
> contextify@0.1.14 install /Users/avramaelony/p/failed-attempt/vega/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node

> spawn-sync@1.0.13 postinstall /Users/avramaelony/p/failed-attempt/vega/node_modules/datalib/node_modules/sync-request/node_modules/spawn-sync
> node postinstall


> canvas@1.2.11 install /Users/avramaelony/p/failed-attempt/vega/node_modules/vega-scenegraph/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:10:
../src/CanvasPattern.h:23:9: warning: private field '_width' is not used [-Wunused-private-field]
    int _width, _height;
        ^
../src/CanvasPattern.h:23:17: warning: private field '_height' is not used [-Wunused-private-field]
    int _width, _height;
                ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
In file included from ../src/FontFace.cc:7:
../src/FontFace.h:27:15: warning: private field '_ftFace' is not used [-Wunused-private-field]
    FT_Face   _ftFace;
              ^
1 warning generated.
  SOLINK_MODULE(target) Release/canvas.node
npm WARN prefer global jshint@2.8.0 should be installed with -g
-
> fsevents@1.0.2 install /Users/avramaelony/p/failed-attempt/vega/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/avramaelony/p/failed-attempt/vega/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote
vega-logging@1.0.1 node_modules/vega-logging

through@2.3.8 node_modules/through

xmldom@0.1.19 node_modules/xmldom

chai-spies@0.6.0 node_modules/chai-spies

tv4@1.2.7 node_modules/tv4

xpath@0.0.9 node_modules/xpath

d3-cloud@1.2.1 node_modules/d3-cloud
└── d3-dispatch@0.2.1

pegjs@0.8.0 node_modules/pegjs

vega-expression@1.0.3 node_modules/vega-expression

exorcist@0.4.0 node_modules/exorcist
├── nave@0.5.3
├── minimist@0.0.5
└── mold-source-map@0.4.0 (through@2.2.7, convert-source-map@1.1.1)

browserify-versionify@1.0.6 node_modules/browserify-versionify
├── find-root@0.1.1
└── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)

vega-dataflow@1.2.6 node_modules/vega-dataflow

chai@3.3.0 node_modules/chai
├── assertion-error@1.0.1
├── type-detect@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

yargs@3.27.0 node_modules/yargs
├── decamelize@1.0.0
├── camelcase@1.2.1
├── window-size@0.1.2
├── y18n@3.2.0
├── os-locale@1.4.0 (lcid@1.0.0)
└── cliui@2.1.0 (wordwrap@0.0.2, right-align@0.1.3, center-align@0.1.1)

uglify-js@2.5.0 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── source-map@0.5.1
└── yargs@3.5.4 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.0, wordwrap@0.0.2)

mocha@2.3.3 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── diff@1.4.0
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

datalib@1.4.6 node_modules/datalib
├── d3-dsv@0.1.5
├── d3-time@0.0.5
├── d3-format@0.3.3
├── d3-time-format@0.1.3
├── sync-request@2.1.0 (http-response-object@1.1.0, spawn-sync@1.0.13, concat-stream@1.5.1, then-request@2.1.1)
└── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.3, form-data@1.0.0-rc3, qs@5.2.0, mime-types@2.1.7, tough-cookie@2.2.0, http-signature@0.11.0, bl@1.0.0, har-validator@2.0.2, hawk@3.1.0)

d3@3.5.6 node_modules/d3

vega-scenegraph@1.0.13 node_modules/vega-scenegraph
└── canvas@1.2.11 (nan@2.1.0)

jstransform@11.0.3 node_modules/jstransform
├── object-assign@2.1.1
├── base62@1.1.0
├── source-map@0.4.4 (amdefine@1.0.0)
├── esprima-fb@15001.1.0-dev-harmony-fb
└── commoner@0.10.3 (private@0.1.6, commander@2.5.1, graceful-fs@3.0.8, install@0.1.8, q@1.1.2, mkdirp@0.5.1, glob@4.2.2, iconv-lite@0.4.13, recast@0.10.33)

browserify-shim@3.8.10 node_modules/browserify-shim
├── mothership@0.2.0 (find-parent-dir@0.3.0)
├── resolve@0.6.3
├── exposify@0.4.3 (map-obj@1.0.1, has-require@1.1.0, globo@1.0.2, through2@0.4.2, transformify@0.1.2, replace-requires@1.0.3)
└── rename-function-calls@0.1.1 (detective@3.1.0)

d3-geo-projection@0.2.15 node_modules/d3-geo-projection
└── brfs@1.4.1 (quote-stream@1.0.2, resolve@1.1.6, through2@2.0.0, static-module@1.1.3)

jsdom@3.1.2 node_modules/jsdom
├── xmlhttprequest@1.8.0
├── xml-name-validator@1.0.0
├── browser-request@0.3.3
├── cssom@0.3.0
├── nwmatcher@1.3.6
├── parse5@1.5.0
├── contextify@0.1.14 (bindings@1.2.1, nan@1.8.4)
├── acorn-globals@1.0.6 (acorn@2.4.0)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
├── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, stringstream@0.0.4, caseless@0.11.0, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, combined-stream@1.0.5, form-data@1.0.0-rc3, qs@5.2.0, tough-cookie@2.2.0, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, har-validator@2.0.2, hawk@3.1.0)
├── escodegen@1.7.0 (estraverse@1.9.3, esutils@2.0.2, optionator@0.5.0, source-map@0.2.0, esprima@1.2.5)
├── cssstyle@0.2.29
└── acorn@0.11.0

topojson@1.6.19 node_modules/topojson
├── queue-async@1.0.7
├── rw@0.1.4
├── optimist@0.3.7 (wordwrap@0.0.3)
└── shapefile@0.3.0 (iconv-lite@0.2.11)

browserify@10.2.6 node_modules/browserify
├── https-browserify@0.0.1
├── tty-browserify@0.0.0
├── htmlescape@1.1.0
├── builtins@0.0.7
├── constants-browserify@0.0.1
├── path-browserify@0.0.0
├── os-browserify@0.1.2
├── isarray@0.0.1
├── inherits@2.0.1
├── browser-resolve@1.10.0
├── commondir@0.0.1
├── through2@1.1.1
├── string_decoder@0.10.31
├── process@0.11.2
├── stream-browserify@1.0.0
├── shell-quote@0.0.1
├── defined@1.0.0
├── punycode@1.3.2
├── domain-browser@1.1.4
├── xtend@4.0.0
├── duplexer2@0.0.2
├── querystring-es3@0.2.1
├── assert@1.3.0
├── timers-browserify@1.4.1
├── deps-sort@1.3.9
├── util@0.10.3
├── has@1.0.1 (function-bind@1.0.2)
├── concat-stream@1.4.10 (typedarray@0.0.6)
├── events@1.0.2
├── parents@1.0.1 (path-platform@0.11.15)
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── read-only-stream@1.1.1 (readable-wrap@1.0.0)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── subarg@1.0.0 (minimist@1.2.0)
├── http-browserify@1.7.0 (Base64@0.2.1)
├── readable-stream@1.1.13 (core-util-is@1.0.1)
├── shasum@1.0.2 (sha.js@2.4.4, json-stable-stringify@0.0.1)
├── url@0.10.3 (querystring@0.2.0)
├── labeled-stream-splicer@1.0.2 (stream-splicer@1.3.2)
├── buffer@3.5.1 (ieee754@1.1.6, is-array@1.0.1, base64-js@0.0.8)
├── resolve@1.1.6
├── glob@4.5.3 (inflight@1.0.4, once@1.3.2, minimatch@2.0.10)
├── browser-pack@5.0.1 (umd@3.0.1, combine-source-map@0.6.1)
├── JSONStream@1.0.6 (jsonparse@1.2.0)
├── syntax-error@1.1.4 (acorn@1.2.2)
├── crypto-browserify@3.10.0 (randombytes@2.0.1, create-hmac@1.1.4, pbkdf2@3.0.4, create-hash@1.1.2, diffie-hellman@3.0.2, browserify-cipher@1.0.0, create-ecdh@2.0.2, browserify-sign@3.0.8, public-encrypt@2.0.1)
├── browserify-zlib@0.1.4 (pako@0.2.8)
├── insert-module-globals@6.6.3 (is-buffer@1.1.0, combine-source-map@0.6.1, lexical-scope@1.2.0)
└── module-deps@3.9.1 (stream-combiner2@1.0.2, detective@4.2.0)

istanbul@0.4.0 node_modules/istanbul
├── abbrev@1.0.7
├── async@1.4.2
├── wordwrap@1.0.0
├── nopt@3.0.4
├── supports-color@3.1.2 (has-flag@1.0.0)
├── once@1.3.2 (wrappy@1.0.1)
├── which@1.2.0 (is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── esprima@2.5.0
├── resolve@1.1.6
├── fileset@0.2.1 (glob@5.0.15, minimatch@2.0.10)
├── escodegen@1.7.0 (estraverse@1.9.3, esutils@2.0.2, optionator@0.5.0, source-map@0.2.0, esprima@1.2.5)
├── js-yaml@3.4.3 (esprima@2.6.0, argparse@1.0.2)
└── handlebars@4.0.3 (source-map@0.4.4, optimist@0.6.1, uglify-js@2.4.24)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0

watchify@3.4.0 node_modules/watchify
├── defined@1.0.0
├── xtend@4.0.0
├── through2@0.6.5 (readable-stream@1.0.33)
├── outpipe@1.1.1 (shell-quote@1.4.3)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.2.0)
├── browserify@11.2.0 (https-browserify@0.0.1, tty-browserify@0.0.0, htmlescape@1.1.0, builtins@0.0.7, constants-browserify@0.0.1, path-browserify@0.0.0, os-browserify@0.1.2, isarray@0.0.1, inherits@2.0.1, browser-resolve@1.10.0, commondir@0.0.1, string_decoder@0.10.31, process@0.11.2, shell-quote@0.0.1, stream-browserify@2.0.1, punycode@1.3.2, domain-browser@1.1.4, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.4.1, deps-sort@1.3.9, util@0.10.3, parents@1.0.1, events@1.0.2, vm-browserify@0.0.4, has@1.0.1, console-browserify@1.1.0, subarg@1.0.0, shasum@1.0.2, url@0.10.3, readable-stream@2.0.2, through2@1.1.1, concat-stream@1.4.10, stream-http@1.7.1, read-only-stream@1.1.1, duplexer2@0.0.2, buffer@3.5.1, glob@4.5.3, resolve@1.1.6, labeled-stream-splicer@1.0.2, browser-pack@5.0.1, JSONStream@1.0.6, syntax-error@1.1.4, crypto-browserify@3.10.0, insert-module-globals@6.6.3, browserify-zlib@0.1.4, module-deps@3.9.1)
└── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, fsevents@1.0.2)
[2015-10-20 12:07:35] ~/p/failed-attempt/vega $
$  npm run build

> vega@2.2.6 build /Users/avramaelony/p/failed-attempt/vega
> npm run pegjs && browserify index.js -d -s vg | exorcist vega.js.map > vega.js


> vega@2.2.6 pegjs /Users/avramaelony/p/failed-attempt/vega
> pegjs src/parse/events.pegjs


> vega@2.2.6 postbuild /Users/avramaelony/p/failed-attempt/vega
> uglifyjs vega.js -cm > vega.min.js

WARN: Side effects in initialization of unused variable perimeter [vega.js:122,8]
WARN: Dropping unused function text [vega.js:13318,13]
WARN: Dropping unused function offset [vega.js:13322,13]
WARN: Dropping unused function line [vega.js:13326,13]
WARN: Dropping unused function column [vega.js:13330,13]
WARN: Dropping unused function expected [vega.js:13334,13]
WARN: Dropping unused function error [vega.js:13342,13]
WARN: Dropping unused variable peg$c12 [vega.js:13218,8]
WARN: Dropping unused variable module [vega.js:1,340]
WARN: Dropping unused variable exports [vega.js:1,347]

[2015-10-20 12:09:29] ~/p/failed-attempt/vega $  cd bin
[2015-10-20 12:11:10] ~/p/failed-attempt/vega/bin $  ./vg2png  ../test/data/cars.json
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/avramaelony/p/failed-attempt/vega/node_modules/vega-scenegraph/node_modules/canvas/build/Release/canvas.node, 1): Library not loaded: /usr/local/lib/libfreetype.6.dylib
  Referenced from: /usr/local/lib/libfontconfig.1.dylib
  Reason: Incompatible library version: libfontconfig.1.dylib requires version 18.0.0 or later, but libfreetype.6.dylib provides version 16.0.0
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/avramaelony/p/failed-attempt/vega/node_modules/vega-scenegraph/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

Thanks,
Avram

**Comment by jimallman** [comment] 2015-10-27 23:38
I tried perhaps a dozen suggested fixes for these errors, with no joy. On my system, these errors were all related to jQuery and its dependencies.

I was able to work around this by using `browserify-shim` to use a prebuilt jQuery:
```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "jquery": "./src/jquery-1.8.3.js"
  },
  "browserify-shim": {
    "jquery": "$"
  }
```

**Comment by aaelony** [comment] 2015-10-27 23:52
Thanks for looking at this. Is this something that affects all Mac Os X 10.9.5 users, others too (or just myself), or everyone?  I googled browserify-shim but I have never used or heard of it before. Just reading about it seems the `package.json` file gets altered then `npm install -D browserify-shim` is run?

What should the `package.json` file look like?  

Thanks,
A

**Comment by jimallman** [comment] 2015-10-28 00:46
A quick search for similar `node-gyp` error messages turns up many people experiencing these problems, while others are unable to reproduce the errors. Some have resolved their issues by installing XCode's command-line tools, or downgrading npm and node to older versions, or modifying system paths, etc., so it seems to depend on some quirk of our systems and previously installed tools.

For what it's worth, [this `package.json` file](https://github.com/OpenTreeOfLife/tree-illustrator/blob/806b88d9008cc041f129d12de107309e52f84ebd/stylist/package.json) is working well for my project. Note that I've used `npm` to install `browserify` **globally** but `watcherify` **locally** (to avoid weird shim errors), so I've [added it to the `devDependencies` section of `package.json`](https://github.com/OpenTreeOfLife/tree-illustrator/blob/806b88d9008cc041f129d12de107309e52f84ebd/stylist/package.json#L30).

**Comment by arvind** [comment] 2015-11-06 19:20
Hi @aaelony, apologies for the slow response, the Vega team has been out at a conference this past week and we're slowly catching up on email/issues/etc. 

From the looks of it, `npm install` only throws warnings, `npm run build` executes correctly, and the error actually results from when you call `vg2png`. So, `node-gyp` and `browserify-shim` should not be the causes of your error. 

Instead, it looks like there's a mismatch in various dependent libraries ("`Incompatible library version: libfontconfig.1.dylib requires version 18.0.0 or later, but libfreetype.6.dylib provides version 16.0.0`") for node-canvas. I recommend following [these instructions](https://github.com/Automattic/node-canvas/wiki/Installation---OSX) for reinstalling those dependencies. If you use [homebrew](http://brew.sh), you might try `brew upgrade freetype`. 

I'm closing this issue since it does not appear to be a bug with Vega. If you continue to experience issues, please continue the discussion on the [vega-js google group](https://groups.google.com/forum/#!forum/vega-js) which is monitored by not only the Vega developers, but also by many Vega community members.

**Closed by arvind** 2015-11-06 19:20 UTC
