### ISSUE TITLE
Modify runAfter being called prematurely?

### ISSUE THREAD

**Issue by arvind** [vega/vega#945] opened 2017-07-28 23:12 UTC
In the following spec, I expect the `paintbrush_store` to populate with tuples every time the user clicks. However, it remains empty. If the `paintbrush_modify` signal is triggered by `paintbrush_tuple` instead of the `click` event, the expected behaviour is observed. In both cases, the warn messages appear in the same order ("tpl" -> "modify"). However, in the first case, the `df.runAfter` is called _before_ the rest of the `modify` function is evaluated.

```json
{
  "encode": {
    "update": {
      "stroke": {"value": "#ccc"},
      "fill": {"value": "transparent"}
    }
  },
  "data": [
    {"name": "paintbrush_store"}
  ],
  "signals": [
    {"name": "width","update": "200"},
    {"name": "height","update": "200"},
    {
      "name": "paintbrush_tuple",
      "value": {},
      "on": [
        {
          "events": "click",
          "update": "warn('tpl') && {time: now()}"
        }
      ]
    },
    {
      "name": "paintbrush_modify",
      "on": [
        {
          "events": "click",
          "update": "warn('modify', paintbrush_tuple) && modify(\"paintbrush_store\", paintbrush_tuple)"
        }
      ]
    }
  ]
}
```

**Comment by jheer** [comment] 2017-07-29 05:02
Thanks! This is indeed a bug. The problem is that modify is being invoked in an event stream prior to dataflow execution, hence the immediate evaluation in the body of modify. Until I can push a fix, I recommend having your modify handler respond to `{"signal": "paintbrush_tuple"}` rather than `"click"`.

**Comment by jheer** [comment] 2017-08-01 23:22
Fixed via changes to both vega-dataflow and vega-parser. The `modify` function now ensures that the `runAfter` call is invoked after the next pulse propagation, regardless if one is currently executing or not. Both modules have had new versions published, and these changes will be in the next Vega version.

**Closed by jheer** 2017-08-01 23:22 UTC
Labels: bug
