### ISSUE TITLE
Axes with only one value don't show label

### ISSUE THREAD

**Issue by domoritz** [vega/vega#970] opened 2017-08-11 04:30 UTC
See https://github.com/vega/vega-lite/issues/2824

Good catch. Looks like an issue with Vega axes to me. 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "source",
      "values": [
        {
          "foo": 1
        },
        {
          "foo": 2
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": {
        "data": "source",
        "field": "foo"
      },
      "zero": false,
      "range": [
        0,
        200
      ]
    }
  ],
  "axes": [
    {
      "scale": "x",
      "orient": "bottom"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/589034/29201427-0526c7c4-7e13-11e7-8671-c45279af1eab.png)

```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "source",
      "values": [
        {
          "foo": 1
        },
        {
          "foo": 1
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": {
        "data": "source",
        "field": "foo"
      },
      "zero": false,
      "range": [
        0,
        200
      ]
    }
  ],
  "axes": [
    {
      "scale": "x",
      "orient": "bottom"
    }
  ]
}
```

<img width="216" alt="screen shot 2017-08-10 at 21 28 53" src="https://user-images.githubusercontent.com/589034/29201420-efda6056-7e12-11e7-98a7-32ab45005db5.png">
(white image)

**Comment by jheer** [comment] 2017-08-11 04:54
Duplicate of #969.

**Closed by jheer** 2017-08-11 04:54 UTC
