### ISSUE TITLE
Force collide with different-sized nodes #1076

### ISSUE THREAD

**Issue by BMPMS** [vega/vega#1117] opened 2018-01-29 10:00 UTC
I'm still having problems with this.  Any help would be much appreciated.  Please see comment at end of ticket above.

**Comment by BMPMS** [comment] 2018-01-29 10:01
https://github.com/vega/vega/issues/1076

**Comment by jheer** [comment] 2018-02-13 22:45
Duly noted! Closing as duplicate of #1076

**Closed by jheer** 2018-02-13 22:45 UTC
