### ISSUE TITLE
Build fails with fresh package

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1295] opened 2018-05-24 20:27 UTC
```
> git clone git@github.com:vega/vega.git
> yarn
> yarn build
yarn run v1.7.0
$ rm -rf build && mkdir build
$ npm run rollup && node_modules/vega-lib/bin/rollup -e

> vega@4.0.0-rc.1 rollup /private/tmp/vega
> node_modules/vega-lib/bin/rollup && node_modules/vega-lib/bin/schema > build/vega-schema.json

↳ build/vega.js
module.js:549
    throw err;
    ^

Error: Cannot find module '../node_modules/vega-parser/build/vega-schema'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/vega/node_modules/vega-lib/bin/schema:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vega@4.0.0-rc.1 rollup: `node_modules/vega-lib/bin/rollup && node_modules/vega-lib/bin/schema > build/vega-schema.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega@4.0.0-rc.1 rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/domoritz/.npm/_logs/2018-05-24T20_25_38_535Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The problem is that vega-lib doesn't have node modules yet.

**Comment by jheer** [comment] 2018-05-24 20:54
The problem is that vega doesn't have a direct dependency on vega-parser here. I've fixed this, but it's not in master yet. That should be resolved by EOD tomorrow.

**Closed by jheer** 2018-05-24 20:54 UTC
