### ISSUE TITLE
enhance vega-loader to support file system (again)

### ISSUE THREAD

**Issue by g3o2** [vega/vega#731] opened 2017-01-29 13:44 UTC
It appears that locally stored data do not load anymore with recent beta versions of vega 3. The above warning is issued in the browser's error console. The spec here below was generated using vega-lite v2.0.0.0-alpha.0 and tested on vega v3.0.0-beta.19. I've noticed the same behaviour with vega 3 specs which were working before the recent updates.

```javascript
{
  "$schema": "http://vega.github.io/schema/vega/v3.0.json",
  "padding": 5,
  "autosize": "pad",
  "signals": [
    {
      "name": "width",
      "update": "data('layout')[0].width"
    },
    {
      "name": "height",
      "update": "data('layout')[0].height"
    }
  ],
  "data": [
    {
      "name": "source",
      "url": "data/test.csv",
      "format": {
        "type": "csv",
        "parse": {
          "annee": "date",
          "poc": "number"
        }
      },
      "transform": [
        {
          "type": "filter",
          "expr": "datum[\"annee\"] !== null && !isNaN(datum[\"annee\"]) && datum[\"poc\"] !== null && !isNaN(datum[\"poc\"])"
        },
        {
          "type": "collect",
          "sort": {
            "field": "annee",
            "order": "descending"
          }
        }
      ]
    },
    {
      "name": "layout",
      "values": [
        {
          "_id": 2
        }
      ],
      "transform": [
        {
          "type": "formula",
          "as": "width",
          "expr": "200"
        },
        {
          "type": "formula",
          "as": "height",
          "expr": "200"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "main",
      "type": "group",
      "from": {
        "data": "layout"
      },
      "encode": {
        "update": {
          "width": {
            "field": "width"
          },
          "height": {
            "field": "height"
          }
        }
      },
      "marks": [
        {
          "name": "marks",
          "type": "line",
          "from": {
            "data": "source"
          },
          "encode": {
            "update": {
              "x": {
                "scale": "x",
                "field": "annee"
              },
              "y": {
                "scale": "y",
                "field": "poc"
              },
              "strokeWidth": {
                "value": 2
              },
              "stroke": {
                "value": "#4682b4"
              }
            }
          }
        }
      ],
      "scales": [
        {
          "name": "x",
          "type": "time",
          "domain": {
            "data": "source",
            "field": "annee",
            "sort": {
              "field": "annee",
              "op": "min"
            }
          },
          "range": [
            0,
            200
          ],
          "round": true
        },
        {
          "name": "y",
          "type": "linear",
          "domain": {
            "data": "source",
            "field": "poc"
          },
          "range": [
            200,
            0
          ],
          "round": true,
          "nice": true,
          "zero": true
        }
      ],
      "axes": [
        {
          "scale": "x",
          "orient": "bottom",
          "tickCount": 5,
          "title": "annee",
          "zindex": 1,
          "encode": {
            "labels": {
              "update": {
                "text": {
                  "signal": "timeFormat(datum.value, '%b %d, %Y')"
                },
                "angle": {
                  "value": 270
                },
                "align": {
                  "value": "right"
                },
                "baseline": {
                  "value": "middle"
                }
              }
            }
          }
        },
        {
          "scale": "x",
          "domain": false,
          "labels": false,
          "grid": true,
          "gridScale": "y",
          "orient": "bottom",
          "ticks": false,
          "tickCount": 5,
          "zindex": 0
        },
        {
          "scale": "y",
          "format": "s",
          "orient": "left",
          "title": "poc",
          "zindex": 1
        },
        {
          "scale": "y",
          "domain": false,
          "format": "s",
          "labels": false,
          "grid": true,
          "gridScale": "x",
          "orient": "left",
          "ticks": false,
          "zindex": 0
        }
      ]
    }
  ]
}
```

contents of `test.csv`

```javascript
annee,nent,poc
2005,883,6383
2006,930,7267
2007,988,8029
2008,1021,9145
2009,1055,10198
2010,5078,10254
2011,1098,10823
2012,1110,11479
2013,1169,12347
```

**Comment by jheer** [comment] 2017-01-30 04:03
I am unable to replicate the problem. I tested it three different ways:
1. Launching from files served from a local webserver. The visualization loaded without issue for me.
2. Using command line utilities (e.g., vg2svg). No problems here either.
3. Launching from files served directly from the file system (e.g., using "file:///"). This failed (as it should) by throwing an XMLHttpRequest error related to cross origin requests.

As you are getting a load failed warning, it may be that the relative file path may be wrong. For example, is the data subfolder in the correct place relative to your loading html page?

Also, this may not be an issue here, but it is often necessary to clear your browser cache when testing and modifying specification files. In addition, make sure all your Vega sub-modules are up to date; for example, you can delete the node_modules folder and re-run npm install to perform a complete reset.

**Comment by g3o2** [comment] 2017-01-30 23:52
Thank you for the detailed answer.

1) and 2) are not applicable for this issue. 3) I've always been using `file:///` and never encountered any error with vega 2, so you're saying this not supposed to work anymore as of vega 3 ? The data are printed as part of the warning in the error console, so the path is fine. I can see the axis but no marks. Just tried to clear the cache but without any subsequent success.

Now I've also realised that this error is indeed not new with recent builds of vega3 but I simply hadn't discovered it yet - my other vg3 test specs use either in-line or on-line data, which works fine with `file:///`.

Here below my (apparently unorthodox) method of using vega 2 and d3.v3:

* a html page with javascript code, as described in the documentation;
* no node, only the vega.js script preceded by the d3.v4 dependency;
* opened via `file:///` in Safari or Firefox;

**Comment by jheer** [comment] 2017-07-11 17:00
Closing out this issue, as Vega behaves as intended. To load local files via the web browser, a local web server should be used.

**Closed by jheer** 2017-07-11 17:00 UTC
