### ISSUE TITLE
Disabling zero in Y axis of Area charts will overflow UI

### ISSUE THREAD

**Issue by keizer619** [vega/vega#348] opened 2015-09-07 11:41 UTC
I have used following configurations on a Area chart where as i have added "zero":false for Y scale. This will overflow UI from the bottom. This can be eliminated by setting minimum value of data set in "y2": {"scale": "y", "value": "0"}  options in marks

  "scales": [
    {
      "name": "x",
      "type": "linear",
      "range": "width",
      "zero": false,
      "domain": {"data": "table", "field": "data.x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero":false,
      "domain": {"data": "table", "field": "data.y"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x", "ticks": 20},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "interpolate": {"value": "monotone"},
          "x": {"scale": "x", "field": "data.x"},
          "y": {"scale": "y", "field": "data.y"},
          "y2": {"scale": "y", "value": "0"},
          "fill": {"value": "steelblue"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]

**Comment by jheer** [comment] 2015-09-08 05:45
Thanks for filing an issue, though I don't (yet) see the problem here. A vertical `area` mark __requires__ that a y-coordinate and height be specified (either using the `y` and `height` properties or the `y` and `y2` properties). Similarly, a horizontal area mark (with property `"orient": {"value": "horizontal"}`) requires `x` and `width` or `x` and `x2`. So the solution you note is the standard approach for drawing areas.

Perhaps when your y scale had `"zero": true` the visualization was still overflowing, you just couldn't see it due to the cutoff?

I'm closing the issue for now. If I misunderstood something about the problem, please feel free to clarify and re-open.

**Closed by jheer** 2015-09-08 05:45 UTC

**Comment by keizer619** [comment] 2015-09-08 06:10
Please refer following screenshot which would make sense. Here graph has been overflowed from the bottom when i make y scale zero. I noticed that this could be resolved if i make y2 value as smallest number of dataset

https://lh3.googleusercontent.com/-VU1hqdfexBk/Ve1tjGOMLoI/AAAAAAAAAdY/Jvp_2yirmgM/s1600/Screen%2BShot%2B2015-09-07%2Bat%2B3.25.20%2BPM.png

**Comment by arvind** [comment] 2015-09-08 16:48
Indeed, the graph overflows here because your area mark still specifies `"y2": {"scale": "y", "value": "0"},`. Perhaps the easiest option would be to switch it to use the enclosing group's height, like so: `"y2": {"field": {"group": "height"}},`

**Comment by jheer** [comment] 2015-09-08 19:24
Ah, I see. The problem is that the y-scale is defined only by the input data, while your area mark is still referencing the zero value. @arvind's solution above would fix your issue but create a misleading chart where the area baseline is non-zero -- this could lead people to misinterpret the heights.

Another option that might be helpful is to use the `domainMin` property of the scale. For example, setting `"domainMin": 0` on your scale will include zero as the minimum value of your scale domain (overriding the observed minimum value in the input data), but unlike `"zero": true` this can be set to non-zero values as well.

**Comment by keizer619** [comment] 2015-09-10 07:12
Thank you very much for quick responses.
I tried both cases on vega editor but still it did not work. Please refer attached image. Here still it starts from the value where i specified for domainMin but overflows even i specify lowest value. Is there any specific way where i can get the minimum values of chart dataset ?

<img width="841" alt="screen shot 2015-09-10 at 12 45 59 pm" src="https://cloud.githubusercontent.com/assets/2918812/9782214/0187610a-57b9-11e5-84d4-685a1764b2b3.png">
