### ISSUE TITLE
vg2png does not work with axes

### ISSUE THREAD

**Issue by seyfert** [vega/vega#623] opened 2016-09-08 16:03 UTC
Any spec with axes defined does not seem to generate correctly with vg2png.   For example `bin/vg2png test/spec/scene.json scene.png` produces an incomplete image.

With the axes in the spec just the background and part of the x-axis is rendered in the png (it seems to fail without an error).  If I remove the axes from the spec then the png is generated correctly.

I am on OSX El Capitan using Cairo 1.14.6.  I have seen other vg2png issues opened from last year that recommend using Cairo 1.2.x.  Is this still the recommendation?  If so, perhaps this should be documented in the Headless Mode section of the wiki?

**Comment by arvind** [comment] 2016-09-08 17:39
Hi @seyfert, I'm not able to reproduce your issue with the spec you provided in your [google group thread](https://groups.google.com/forum/#!topic/vega-js/mwdcRZKRjDA). Vega also runs through both `vg2svg` and `vg2png` for all example specs, several of which have axes and legends, as part of its testing routine and I have not noticed any issues there either. 

I'm running El Cap with Cairo 1.14.6 as well (the 1.12.x recommendation was to deal with some bugs in Cairo that have since been fixed, hence the lack of recommendation on the wiki).

To help debug, what versions of vega, node, npm, canvas, etc. are you running?

**Comment by arvind** [comment] 2016-09-08 17:40
As this does not appear to be a bug report, I'm going to close this issue out and move the conversation back to the google group thread.

**Closed by arvind** 2016-09-08 17:40 UTC
Labels: question
