### ISSUE TITLE
Vega : Problem with the move event on Firefox

### ISSUE THREAD

**Issue by rdelavalle** [vega/vega#1581] opened 2019-02-19 10:41 UTC
Hello,

I'm trying to create a network graph with Vega.
When I test my graph structure in your editor on Firefox, I can't move my nodes.
However, in the console, I can read : "[Info] No error or warnings".
I tested on Edge and Google Chrome and it works perfectly.

Below the link to my example :
https://vega.github.io/editor/#/url/vega/N4KABBBEDODGAWBTAtgQ0gLlBHZIBtUA7AcwFdUTFNIA3RE9AGnFz3oCdoBLAeyJoBmAHQAGMZFZgAvixyQiqZNQyRE0aKm6Q5UAO7cAJgBd4mAIwAmUaN140HANY1UHRMymQk3EvGOYANhs7SAAHVENDblJMW08eEkV8aEwAbSkcbDZ5RWUaWAAPHQy2SDJQw1RjFUgDE3gwAHowS0ls2RKwLOy8XJrYAE9inqhyyuqab19jJpa2tg7s7uyFJRrqguMABV4eYz4BOxXaVHwyFUE4kbwAI2jDTGWRyGjQsn9VDmIqYeuoZGisSOzzQRQwAFYrn88NBqqELJ0cNJOos2E9cKs8qoiLxDIgAMLwVw-YEYk5nFQAWnMwURUDuRAeWDpGNe7xoX1I1FJKwBAgw1Np0PsqDBNJ5pVhiHhGHMLOR7VJ6Jyaxo+GijgAItxYcRYNyWXRTucLJcJbd7o8WfI2R9IJySdb-oCIeb5KDMNYoX8YHCEdcFQslYa+mqNQBlYwcXiOA3XI0Uz3myAMpnK0q2jnfOPQyB82LCcxu-6iize+NSmXiOUBlHB+Oh1QAM34-mT5JNqk0RGglOgiA43Cbvx6KctzOFLyIbzt-fwiFgbadeF4oX2-BSGHSwvk3d7-cHw+LGIPQ5Hk+Q-F24X18z+AF15XXOuneqrVOqAUv4x2VOXSqmVqTpmnzZueIIuv+o4erKkLHr60r+iMga4KiuCvpiNS6vssDgWSxoqE2pz9smgETrmIGQAgC6ODcvBFE+iqdC+IbvlO0ChAuxi8BweHyL+mBEGQ+D4MmbioIumBRucyb8Gky6visiD0EQxibjAAzIHR+AYJeZD9rwnB8c8YxVDU4xkMgd4BseimlMpiCqep0Cadpum8PpiAed+O54KZEzYsJ+DWchLKPkxSysVikD7FGOajgJqgAIJJAM-ZgAAksgN4+aO-k1NEHFcTxYAAPxgIVnGLjxwh9BAGBgAA5ClpxpYgmXZRJxiNSFMj1s8jZUbw+A8cZ7AETQY1lBUZk0JVxUcGVTWwMNJUYI1ADU83VRwwgrSNi0NY1jV4M+kXxnicCDmuBw0JGZlgCcg6oDc85gC2i1ddw9BgDieLvdwBRgNh+nCFNg1NoDU2JVB8hyVuCnLvIDlOTQLlacN7med5qQAIQo8Ywg3O83E9veTBgAYjK8HoWP9uUY0rPlNCiL1EXQnZGIE85rmY3pBlGce8jM82gNgAAPuLYDmGzQaI75eDczQqTo25-OIIYNNEBTVOa7T6vlPeYAAHyU-cNN0yghmILjjOlCLkCtELUAfbeGDSYgy4odk4Vy+dzyXbA13rvykAAOJfKEDR-e1l6wmAbj6qp+ADBVqkDl1Gtm6YYPJoNMfQxNGBCSJsn8tuHNI1AStdrzOnq9bvHO35M0BZAkNAwAvN30tLdw1TIAAFAAlGADUF17YVnWihqB8Ht2qAAYoQJBgNxCfqMYrgzIvPH6sD3DIMJVQHGA5T8GA4yoGACDZtAudRTUbi6hwuXHEXRHJIgZfycKnPIypNSQEFZQASEkGgHdZY9DQpOB2HcTbSygUiKe7N0KPxcIub68V36JmLkFH+CM-5V0VoA9SGxjCW0bnbDEDsLLIGEPcRADFhQwJGP-aupCaAN04HjAmDCB73mocLVuNQS7BUntcX2qF+qjkGuQ8M3AABe2DSiJWsCiKQ5NPBX1-jPBsbEY77g8hwW87YCKbgrn8dheAk5xRoAAYkXovVmzdMI0HxElLYAA1IRUBGFglhs8fao1VCOJsL4vAUZUBNkhrhDAlwhS+ReGgH4qhGiH0oOoRoEdUBR3SUQFswhQgxFcdAIknEaAAFlbDCHBAAGWEAEJgwgAAcDTwTNPMHUoslJhCCAaYIJgvSAAsdTbDUjqb0wZIzJk9L6ZM2pnSFlNNaWM5p4IABaSCICsJ6NYtxqhwwAAkADyWwAD6i8kr4gACrhgiVOPEYpXHBN4qEgA7PiFxxCYpfBidwOJlhISBNHBk1JkB0kpKyTkvJNyABCDTikkAeWU3J5luBKH4A8L2tkfmDSSpUk5ABVAAcjc854YTl1M1A8-xSYfmvIcYvTU3yFa-OibEzACSQUrDBTUSFmToDZMjvARo+0iklJ+aiipqhKmUnEAATiGYqo5iqvHiHeeCI58rhAKq2Ti+WSTBoAFFLx4lpYyJhXKXmrTeZAex+JwRwoeVE-5gLgWuL5TQAVVAhUwtFTcSIErkWlPKeizFjJtl9UNTuA5kBwwDnoGQRacKTkWqeZgYZNqDoOMsElJKLq-mcowECxJsavVpL5X6kVjRoAcFoMGlFYaaBRAjdilhuK2WDQAIoUFUv3FRPo6WugZbahxmp3ky1ca64tXoeUZihd6qtwrcmiuiIUpFTa0X5G4CY+cUbdn+1jYNLYg4iiestWCJpo6c2hInVOn5M6AWehsPO1ki7K1Qurau-JG7JVsulf0XdsB90GqIV2tiXjHLVBSBejNGB3nZpCfalp7yaXTqLc+ktr7PUfohcu-1jQiL90baG7dqhYDAdAx2mNk5BoACUUA6kHfGYdLSkN2vsYId5xrC0cqw3O3DmSl1fpXXkk5cKABSpGpXNtlTqpVCnVW6vVbq7Vir9U0fA0atijGVJkEvuoR60H1DpqtRgJVN7kNcZ43xt1L6y3ATwz66FNaJPSc3WRmVkA5WKuVWptVKqFOaehIevROnopQfTtAMAL1+zRbM2KN98hGWhO47xjD-HAU4Z+RW-DonCPuZkwBuTPmFP+YVcphVqnKvBYPZ2iLNQoswbAKEZ+JnYO5cvRYIsVnOPpbs7OnLbK8sue-eJqTxWkmAaqeVpTgW1N1bA5XCD0UWop3SpdYzCW4PmasBxhxqAjuDYE8NpJo2CM1tCAC7ilJNawCm7Gmb8m-PzZU0FjTB6UF+3C7IgxuJ1B3aqB4Csxi3YKAB0Y5Nt5p5oP0dFdURBHB3fUEnSoqk+xg5Y1AX8FjaO5mgFjoEj7iSIA+JYadAxvP2KO8OZbVipVE5LdO0nHx2OPqpzUGn0T6v459IT6HKgKck44FQD4lm2XGE54dnn9Prj7IFyYoXLPRdk7LJT6ntPefaae0z4XkvWc9Y11zrXcu2GM8F5gCXSSt6q4+PtjnmvZcsO+9Ili8OaiI8cL2QOjl0dv0lEzggGoUdwD98QYwmPLew8yOgj8IfLyqQj1HpXhcKR4515ORXbtktQFt2LzAHTHdc-MKgVmZu9kW9TxgXPkTDcYGvZL6XoTS-l60yt6bTOi8G7t5gRDxeHGt+1x33XluG8q4Lwh43g+y-D4ZwBpnteYr1-7036nQ+JEjCkUiGRKxBpe97InreqkprZ89wn1syez9TQ+mgD4nMYrN8gAAK0J4cZcYRoycVfkMePSPD+X4n6MQ-Zw4DRsRe6Uhwqaiagp6mKGi466Lz6d5j69Y96T76425P72JEToAV5HpZ5M6DIi6T6oGYHU44Fz7y5V5uxZrEFq7xLT6hIUGb49Db47K76lD74ai9hQHoaGjX5-7I68GwHY54C35VDAI+hS7eav5yTwRtargDhS5hj-6QHQFQLezsHu5gHRQxxA5byn5B6GL6G4GoKx4e5oyIDziLgayGFj4Q54gmFTRRI9i36IFUFr41CQz4DVBNw-JMJtZzQ9hVTcSLQABkYRacRUO0DCl6YAPcdCsRGaLBPsMeEAGEXBSOoeaOEedh1eweqhvujIuRaRXQceBRyOR+uRyYAhFRABSeQBZh6R5REBvBeR4OB+ahNKpRGRbEIG+kvhnWP45i7h5uI2TIkAxq84ygqkN80GXwwUB2oSzibeoWDW5aExNyL0+6Sx9qnyqxfwYWoBGx7iq0RARAohKwqW9qzKBxNkfOrGExGUBSPEd+t0ux9i96lBYx52Exi8WgAePo1x9iqG3R7eSBJxqgJyNwz+auHxA2eBv2wEExmovAsAlk0GDywJ+aBaiJxxyJNAcKqA-YWJY6oSjqzqeJ5hvxd0iaiAyapJt69qeauJ4JHhNJqgNynI0A4hIcjJ1mi84IrJaxDxzwRgNAi8AK8A3AA4-JnGNIlJbJPxkJkAGUNyi8cpDiAQwydxoUkiPR5R-RUoXATs8BIxhCI+BJqgVRJ+Hx5gSUup0C6xVpkARR-umpoS+aGpVJzR4xhJ6hHxVywphxruO+2hf20URpgxggae5wGelpFEExAA0lsBlFut5tUusg0ism0osoWN0kMvMn0oWaMuMl0lMiWbMoWf0r0h0vmb0jmWsrUiFocc6Yme4tvLwCQCKjKemeGonu2iKZnu2aoIxrCP3O8O8bJuRmVj0uYEcuYF4vOdSC2fccOUOn8fwJgvwBcYsdOd5pRnutQCkWwGwTIJoiEHAKcKZhafiZwX0WOsmNITUDxFEOAsmJrGgC6A-johRmcMaUMbmJDFYRMeKfKGJGBORD6L+VRP+YMdQu3DKfgBMYysAW7vgfeZGbanUhqM4U-q+dEKcFNJ+VoPyD+cDvkHBQONAKaZOMBchXNIOU6YaA6CoORQYX+QMdRbRUBUhShWOmhWGRhRiINIBiSgDnhd5gRe+bPLwF+WRR-jBVGdRTGfBPRaBUxU0RiKxZIRdBRZxQBapR-upWjM2oJTsheZ4POFQIyPGXeRiLFPuqoPiB5POMmoZjFrwDCWToBaOIosOqQaODxDKSfqoHRMYNxMgJSIONMDftwCJPkI+YaI5CtOalBRWHXJuPsiZm8qAMQpocxZOIQDcFYVlT8iLHlQrAVe0OZdGsJfII5TULvBwMoL5SsP5d1rKLJIOJiaoNxKEJSPOE2ICbuKVmJRJcmClRJelc8KrMNGVWyjlVaPlT6XgMVaVbpbmBVSACtS7rWFpRhLCNGLGIlQdDhUjlNMFb1SmLwBFXJYNYgMNc4f3E5ZADhY5G1aUB1fBoFUpEQKlWxR-nNckJtT6EtTNU9nJtYjgp2LOYsqIAuVGjVVVSeahBojgFou6K4N7qMWURYdiJDpJVhHXFNN9eZuILQfGE2NGFZBDSsDBXoTouBYaPDJYuybGlGD4FQHapAq4makOL-g4ZcaouaYhV3D3OYEtMAE2AUMXADsIAUBTE2AMHLXiMIAMNIGPF0DLRgAUCPErSrQMCPNIN8ZXpLjFdzTQLjLzT8vzcrTQAXK4ggaoNLbLb9Pgu9Cre7SJCbajRjZNf9dNQ-uDQrlDcQvICZV2GZVVa4t4cFHTbmAzQDk4c3BHXxadaNPlaUlGDGIgAAOpGCmCg2TiJTDK7VDlbUiLF2zVKKA0gIuzp19WYa4Tl0hlrnPAuE8mvG431Ud1P6uzC2si+EnwbhcqOa5jPy2737h2gI+DgKfCbzbxI1aEAZbw4TV385z1EVdhr3PpZ0-ID12UKzQ2lAD35BLWp2lBggn2jhgLb1UTML11CVP1QC-430rB33x1URDAz1o1P1HHs1P3tx7yiJ0SGBDCX0nhxSkBF0J0gIwBb1f0xyEik7L3QK-0APKlANn2CERIrAH4qHI5unVG-3yBRC6j-V10v0niIOEPagUMw7UPnn-2QPv0uwgOEN4OlAEOCGUg2kjVJLkPH5uxsM0OJD31e70PCPHlMPVUV0gKiPAP5Fe5cMYg8MVFdGqNkM6jSMb0Aa0OCFSN6gyPUNyNt2+RnnI1b4GnxjPk0DkJTTRDD2YL0CYCfwkSGhk3PKGg3DElWHRBUM+iJQxSrgaHJjU1yV6NQBJ2XRhPJWB1pXB3py5U-KnBz1RMJRFxURLX72S5MLT3YON2ulVCWS1Sqit3t0+jbVsrX2-2IUgU0CP07iYMYhv11OR2QAQN1O8AxL9gFPUMIPiNf3kI7B7C3QYO5NJK+NzgBMZMw01AAiRDUa+QtMR2thzOSgGPAONErOuKfj9wbNiPz3B5fhoOrPsOqR52IA+B+A90JnwMwZ2j3DA6DyNRzhcQayNQUyNT+JfOXwlP0L+LDxaM45ZPaSaW7O-2KOJRiITMKyWMLC1W7LhkrB2OqDhBF3JheMFi-Wn000ZPFMcUaPEM7OFVinJNfSuMYDuPfzxMA0Esh1So50nVwPDG4L2qm4o1Kl5RV2suSjMv52F1mB8uZO4KCCTNPYCuHNp0NN9XS4VN6nIRPncluG3mAO5hosVEYtmBebn4XEopY4AAaLaALwgZ+CtBrguAAmia8YKU+a102gWTsa6oIkfnmThaxPmTja666a+64TD-XtdYwdYaJq9q6TcOtWOE-iyK4S+gLw-w3E6xhSy44RMRLS-GFNYkx-oy6vcdYE2ysE8wTHUy-m5qMScKzfQmJ2GzfXd3tQ2XU-Qi+g9y0zLywrgKwXfUNK6C7gpYBK1nlKyKysB03Ywqy20q6Gyq93Wq1gxq0-l7uG7qyoYPbuEa7a-a1jp69QYgD64S5u4LurS6qzi6-u-Qv69u068YHu266zke37RAGebshhGG1UDq545G4WNG5E7GzBa0eoczcm84-sFSzSwHfS7G7m9NkO1W8E9znTiW3m7neW2Uj2+NLgrWyAhgS-Y2-Xc21Y62R-tU9B-m127A1W5-YQ5GPm2c9nTR8O6fUU2O1y6FoBx3dOy1Xc-ZbYwuxqEu-uTUK4LhKUuu763a-Qua+ejuze6aw68e3bqe7e3bpezbqzjJ+J8IBe4G6x-qSGzx95g48mE4xnKm24+m1iwFeB0HTm8k4c5ALU0A5R6oHUJi9070-QZSOCAO7mG00A4lDWJC2ynHWh9WzUK9BJM4N5z6C2KpAosoiF-5154h0kmk4kAl1kzFbc+O1pW2+MAWxq-kyF05zFP3G4Gcw+8wyAdSaOJq4Z4aMZ18KZ9S+Z3S9Z5OFB7Gg5-XYM8cy5++0Az002H05gJ51F-GL5914l2N88MFwx-hOy+F7AJF8l7GjF8YHF-l7Gv56INN6OKlwpX5xlzc-4Nl1VyZO24+oV3N7uFs6hSx+YxO3-Y+yANIEAA

The error during the move event on Firefox :
![vegaconsoleerroronfirefox](https://user-images.githubusercontent.com/47776443/53008565-fa61bb80-3439-11e9-8b91-6932a837eb2d.PNG)

Best regards,
Rémi DELAVALLE

**Comment by jheer** [comment] 2019-02-19 17:44
The problem is that your specification is invoking the `x()` and `y()` functions in your trigger handler, which exists outside of an input event handling context -- internally the `x` and `y` methods try to access the current event object, which in this case doesn't exist.

Here is the problematic line `"values":"fix === 1 ? {fx:node.x, fy:node.y} : {fx:x(), fy:y()}"`.

The reason this still "works" in Chrome and Edge is that I believe they make `event` available as a global variable, though this is not part of the official JavaScript specification.

One solution is to capture the x and y coordinates in a signal, then reference that signal in your `node` mark trigger handler. An older version of the Vega force directed layout example exhibited this same error, but has since been fixed with this solution: https://vega.github.io/vega/examples/force-directed-layout/

Hope that helps!

**Closed by jheer** 2019-02-19 17:44 UTC
Labels: question

**Comment by rdelavalle** [comment] 2019-02-20 13:09
Thank you for your quick answer !
Indeed, after having modified the fix signal, the graph works perfectly on Firefox !
