### ISSUE TITLE
Incorrect centroid behavior on antimeridian-split shapes

### ISSUE THREAD

**Issue by nyurik** [vega/vega#992] opened 2017-08-19 16:05 UTC
![ezgif-3-77145c72a2](https://user-images.githubusercontent.com/1641515/29488304-fe997540-84d5-11e7-852c-518138cbdf85.gif)

As observed in the video, New Zealand centroid is slowly moving across the whole globe when it is broken in half by a virtual "anti-meridian line" - the longitude which is exactly 180 degrees away from the screen center.  This affects all geojson features, and especially large countries, as they are more likely to be broken up - e.g. observe Russian centroid moving as well.

Ideally, geometries's center should not be affected, regardless of the current viewing point.  Also, this might be an upstream bug, but adding here to track it, as Vega users might be affected by it like we were.

**Comment by jheer** [comment] 2017-08-19 17:23
I suspect that any issues here may stem from d3-geo: Vega simply invokes the `centroid` method on a `d3.geoPath` instance. I recommend testing directly on d3 and filing an issue there if warranted. If unable to reproduce with D3 alone, please share that here for further testing!

**Comment by nyurik** [comment] 2017-08-19 22:39
d3 mentions some of the antimeridian issues in the [readme](https://github.com/d3/d3-geo/blob/master/README.md) - not sure if Vega should do any projection specific geometry handling.  I haven' used d3 for this before, but hopefully it won't be too hard

**Comment by jheer** [comment] 2018-02-19 21:23
Closing, as it is unclear if there is anything to do at the Vega level here. Feel free to reopen with more specific requests as warranted!

**Closed by jheer** 2018-02-19 21:23 UTC
