### ISSUE TITLE
Incorrect GeoShape rendering

### ISSUE THREAD

**Issue by rezpe** [vega/vega#1418] opened 2018-09-22 09:38 UTC
This shape renders incorrectly as explained in  vega/vega-lite#4165
```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "autosize": "pad",
  "padding": 5,
  "width": 500,
  "height": 300,
  "style": "cell",
  "data": [
    {
      "name": "source_0",
      "values": {
        "type": "FeatureCollection",
        "features": [
          {
            "type": "Feature",
            "properties": {},
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [-3.57330322265625, 40.57849862511043],
                  [-3.570556640625, 40.59101388345591],
                  [-3.7298583984375004, 40.62437645591559],
                  [-3.9358520507812496, 40.57224011776902],
                  [-3.8287353515624996, 40.50126945841645],
                  [-3.7902832031250004, 40.48873742102282],
                  [-3.57330322265625, 40.57849862511043]
                ]
              ]
            }
          }
        ]
      },
      "format": {"property": "features"}
    }
  ],
  "projections": [
    {
      "name": "projection",
      "size": {"signal": "[width, height]"},
      "fit": {"signal": "data('source_0')"}
    }
  ],
  "marks": [
    {
      "name": "marks",
      "type": "shape",
      "style": ["geoshape"],
      "from": {"data": "source_0"},
      "encode": {"update": {"fill": {"value": "#4c78a8"}}},
      "transform": [{"type": "geoshape", "projection": "projection"}]
    }
  ],
  "config": {"axisY": {"minExtent": 30}}
}
```

**Comment by jheer** [comment] 2018-10-08 18:17
I believe this is a duplicate of #1405, which arises from some assumptions that d3-geo (our underlying implementation) makes relative to the GeoJSON standard. If this issue in fact stems from a different problem, please comment here and we can re-open.

**Closed by jheer** 2018-10-08 18:17 UTC
Labels: duplicate
