### ISSUE TITLE
Symbols position affect chart height

### ISSUE THREAD

**Issue by floribon** [vega/vega#346] opened 2015-09-05 01:35 UTC
Because some screenshots are worth many words, here is what I obtain when I add/remove the datum `{"latitude": 89,  "longitude": 0}`.

Without the remote point: the map looks good and fits its container
![screen shot 2015-09-04 at 6 31 37 pm](https://cloud.githubusercontent.com/assets/2934743/9697057/3ca6ce40-5333-11e5-98c8-be73d1ead636.png)

Adding that point increases the height of the map, although a "height" is specified and padding is strict.
![screen shot 2015-09-04 at 6 31 48 pm](https://cloud.githubusercontent.com/assets/2934743/9697058/41db4594-5333-11e5-95ed-1036735211b6.png)

The problem still occurs with any kind of padding, but only happens when the datum is too "high", the lower one (`latitude -89`) doesn't affect the map, we simply don't see the point, which is the expected behavior.

Here is a spec to reproduce:

```
{
  "width": 900,
  "height": 560,
  "padding": "strict",

  "data": [
    {
      "name": "states",
      "url": "data/world-110m.json",
      "format": {"type": "topojson", "feature": "countries"},
      "transform": [
        {
          "type": "geopath", "projection": "mercator",
          "scale": 100, "translate": [0, 0]
        }
      ]
    },
    {
      "name": "airports",
      "values": [
        {"latitude": 89,  "longitude": 0},
        {"latitude": 50,  "longitude": 0},
        {"latitude": -89, "longitude": 0}
      ],
      "transform": [
        {
          "type": "geo", "projection": "mercator",
          "scale": 100, "translate": [0, 0],
          "lon": "longitude", "lat": "latitude"
        },
        {
          "type": "filter",
          "test": "datum.layout_x != null && datum.layout_y != null"
        }
      ]
    }
  ],

  "marks": [
    {
      "type": "path",
      "from": {"data": "states"},
      "properties": {
        "enter": {
          "fill": {"value": "#dedede"},
          "stroke": {"value": "white"},
          "path": {"field": "layout_path"}
        }
      }
    },
    {
      "type": "symbol",
      "from": {"data": "airports"},
      "properties": {
        "enter": {
          "fill": {"value": "steelblue"},
          "fillOpacity": {"value": 0.8},
          "stroke": {"value": "white"},
          "strokeWidth": {"value": 1.5},
          "x": {"field": "layout_x"},
          "y": {"field": "layout_y"}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment] 2015-09-08 05:34
Thanks! I tested this in the vega-editor running vega 2.2.3. A couple items to note:

1. The `auto` padding works as expected for me. The visualization size is set large enough to encompass all marks.

2. Setting padding manually (e.g., `"padding": 0` or `"padding": {"left":0, "top":0, "bottom":0, "right":0}`) also works as expected for me. However, I suspect you want to update the projection such that `"translate": [450, 280]`. Once the translation is corrected the map is centered and the errant points are drawn off-screen. (Note that the auto-padding of `strict` mode was re-centering the visualization for you when the errant points are excluded!)

3. The `strict` mode padding, while not resulting in a desirable visualization here, is working as intended. Here is how strict mode works: (1) the visualization is rendered and the bounds (size) is calculated, (2) the internal visualization width and height are reduced such that any excess padding now fits within the absolute width/height bounds, (3) the visualization is then re-rendered at the new settings. In particular, reducing the visualization width/height will effectively reduce charts defined relative to those settings (e.g., when scales have `"width"` or `"height"` as their range). However, the map projections as defined here make no reference to the chart size, hence `strict` padding mode has no effect on them. The maps and points do not resize in any way and the view is simply cropped to the upper left corner.

Since there is technically no bug here, I am closing the issue. I suspect in this case what you want to do is set the padding to a literal value (e.g., zero). However, if you would like to make an explicit feature request detailing an alternative behavior for how `strict` mode might work, please feel free to open a new issue!

**Closed by jheer** 2015-09-08 05:34 UTC

**Comment by jheer** [comment] 2015-09-08 05:52
p.s. if you want to plot data near the north or south poles, don't use a mercator projection!
