### ISSUE TITLE
Text-align offsets mousemove interactions

### ISSUE THREAD

**Issue by kevinmickey** [vega/vega#344] opened 2015-09-02 02:39 UTC
In the vega-editor, I made one change to the css of the container element:
```css
.vega-embed {
    text-align: center;
}
```
Examples like brush, crossfilter, index_chart, force_drag, linking, and overview+detail all seem to have their mousemove interactions offset, proportional to the margin between the container and the chart.

I tried changing the expression for the signal to be more specific - like in overview+detail, I tried eventX('overview') - but that did not help.  I'm new to Vega, so I might be missing something obvious...

**Comment by jheer** [comment] 2015-09-03 06:31
Thanks Kevin! This indeed is not the intended behavior.

@arvind: It looks like the issue is that in `parse/streams.js` we compute mouse coordinates relative to `view._el` (the enclosing vega `div` element) rather than the contained `canvas` or `svg` element. In this case, the container div layout is changing in response to `text-align: center`, leading to the distorted mouse coordinates.

**Comment by arvind** [comment] 2015-09-03 15:37
Thanks Kevin! This has been fixed in d082742 and is scheduled for the next patch release of Vega.

**Closed** 2015-09-03 15:36 UTC
Labels: bug
