### ISSUE TITLE
Incorrect FIPS code in County Unemployment Example

### ISSUE THREAD

**Issue by kieferaguilar** [vega/vega#2796] opened 2020-08-12 19:31 UTC
The "County Unemployment Example" uses `data/us-10m.json` and `data/unemployment.tsv`. In both of these files, the county ID for Oglala Lakota County, SD is listed as `46113`. However, the correct FIPS code is `46102`. See [Wikipedia entry for List of counties in South Dakota](https://en.wikipedia.org/wiki/List_of_counties_in_South_Dakota).

Side note: There is no `46113` county FIPS code, so this error is not a transposition with another county code.

**Comment by domoritz** [comment] 2020-08-12 20:04
Is this a duplicate of https://github.com/vega/vega-datasets/issues/171?

**Comment by kieferaguilar** [comment] 2020-08-12 21:11
Probably.

Without more digging, I can't say whether Oglala Lakota County, SD changed FIPS (and if so, when) or whether there was an error. Regardless, [us-atlas](https://cdn.jsdelivr.net/npm/us-atlas@2/us/10m.json), as suggested in https://github.com/vega/vega-datasets/issues/171, has the correct FIPS code.

Looks like either https://github.com/vega/vega-datasets/issues/145 needs to be reopened or a separate issue for census datasets should be opened. At your discretion, this issue can probably be closed.

**Comment by domoritz** [comment] 2020-08-12 21:25
I think we will eventually update the unemployment and counties data but for now, some data issues can be useful for instructional purposes ;-)

Vega datasets is not supposed to be a reliable data source.

**Closed by domoritz** 2020-08-12 21:25 UTC
Labels: bug
