### ISSUE TITLE
Questions about fitting scale range to group mark's width and height

### ISSUE THREAD

**Issue by kanitw** [vega/vega#713] opened 2017-01-14 05:50 UTC
## Background 

I try to make facet layout works as in Vega-Lite 1.0. 

In Vega 2, we can simply set the range of facet's column/row scale  to `{range: "width"}` and `{range: "height"}` and it [works fine](http://vega.github.io/vega-editor/?mode=vega-lite&spec=trellis_scatter).    For example, here we facet a bar chart by `row`.

<img width="1289" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/21952587/29b8e7e8-d9d6-11e6-9fca-eab73535fc3e.png">

However, doing so in Vega 3 (like this [output spec](http://pastebin.com/tLJc9wS5)) makes the height too tall, leaving an extra gap in the middle (similarly for `width` if we apply `column`).

<img width="1289" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/21952595/68c246dc-d9d6-11e6-832f-3a9a41ca449e.png">

## Questions

1) Is this intended?  Or is it a bug?  

I know that layout calculation changes in Vega 3.
If I understand correctly,  `{range: "width"}`  and `{range: "height"}` refer to the top-level width and height that already include the padding, and thus is larger than the calculated width/height.  (But I'm not really sure.) 

2) Doesn't scale's `range` support mixing values with data sources?

Assuming this is a bug, I inspected the `layout` data source (`ved.view.data('layout')[0].height
`) and found that the calculated height is actually 432.   

Replacing the row scale range with `[0, 432]` produces a reasonable output.

<img width="488" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/21952603/beb33ede-d9d6-11e6-9d45-d417d9deed49.png">

But hardcoding the layout value would not work for Vega-Lite, so instead I tried setting `range` to `[0, {"data": "layout", "field": "height"}]` but it breaks the visualization (nothing is shown) and a mysterious error is thrown in the console:

```
Uncaught Error: Unsupported object: [object Object]
    at error (http://localhost:1233/vendor/vega.js:806:9)
    at parseLiteral (http://localhost:1233/vendor/vega.js:28231:7)
    at http://localhost:1233/vendor/vega.js:28372:12
    at Array.map (native)
    at parseScaleRange (http://localhost:1233/vendor/vega.js:28371:16)
    at parseScale (http://localhost:1233/vendor/vega.js:28217:20)
    at http://localhost:1233/vendor/vega.js:28797:5
    at Array.forEach (native)
    at parseSpec (http://localhost:1233/vendor/vega.js:28796:24)
    at parseSubflow (http://localhost:1233/vendor/vega.js:27944:15)
```

I guess it's fine that this is unsupported, but **we probably need better a log message**.  

3) In this [spec] (http://pastebin.com/iyUxPkNf), I tried adding extent transform to the end of the `layout` data source's transform. 

```
        {
          "type": "extent",
          "field": "height",
          "signal": "h"
        }
```
and set `"range": [0, {"signal": "h"}]`, but the output doesn't seem to have the right range and show output as if the range is `[0,0]`.  

<img width="498" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/21952800/2b9330ba-d9da-11e6-87ec-f6e2c7ac9937.png">

4) Finally, I tried declaring signal my own signal instead by adding:

```
signals: {
   "name": "h", "update": "tuples('layout')[0].height" 
}
```

to the top-level spec and and set `"range": [0, {"signal": "h"}]` (See [spec](http://pastebin.com/kRVrfBD8))

Now the output looks fine. 

<img width="507" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/21952708/91dc351c-d9d8-11e6-8030-1b7ec92779c0.png">

Before I proceed to fix this issue with this method, I would like to hear confirmation that this is a suggested way to implement this (and that I did't overlook anything important or run into a bug) in each attempt above). 

Note: This issue is not about scales for nested faceting that we discussed earlier today. 
I'll file another issue later once I have a more concrete requirement.  But nested faceting is not required for our `alpha.0`.

**Comment by jheer** [comment] 2017-01-14 06:31
Responses:

1. There is not enough information here for me to determine if this is a bug or not. I do not know what Vega spec is being generated so I do not know what exactly is causing the observed behavior. In any case `"range": "width"/"height"` simply uses the width and height signals defined in the nearest enclosing mark scope (this will be the top level unless the width/height signals are overridden within a nested group mark). Check the [vega-parser scale code](https://github.com/vega/vega-parser/blob/master/src/parsers/scale.js#L189) to see where the range comes from.

2. `[0, {"data": "layout", "field": "height"}]` is not legal. However, for ordinal scales (including band/point), you can do something like `{"data": "layout", "field": "height"}` (this needs to be a legal domain definition, your example is not). In any case, this approach only works for generating a list of unique values. It will not (in general) give you the two-element spatial array you want.
Also it looks like you may be using an older version of the Vega 3 parser. The error message issue you note _should_ have been fixed in vega/vega-parser@e218cc5502a4147505bc6f163a31cb7979a9ccb4. (But now I notice some other places in the scale parsing that need better messages, so I'll fix those soon. Thanks!)

3. Extent generates a [min, max] array. Did you try `"range": [0, {"signal": "h[1]"}]`?

4. This is valid, but looks a bit hacky. I'd work through the issues above first. If desired, you can collapse this to use an expression directly: `"range": [0, {"signal": "tuples('layout')[0].height"}]`.

In any case, I think it would be simpler to just share the Vega spec generated by Vega-Lite here, and work forward from that!

**Comment by kanitw** [comment] 2017-01-14 07:24
Thank you  Jeff.  

1.   Maybe it wasn't clear, but I included the original output Vega spec above. 

> However, doing so in Vega 3 (like this [output spec](http://pastebin.com/tLJc9wS5))

From the spec, currently I don't have `width` / `height` signal or top-level "width" / "height" and use `autosize: "pad"`.   I only apply the calculated width and height to the size of the Vega-Lite's root "main" group mark.  So I wonder whether the "height" is too large due to the `autosize: "pad"` or not. 

2. Okie.  I'll update to the latest version. 

3. Oops!  `h[1]` certainly works.

4. Yeah, that's why I decided to ask.   I certainly prefer 3. to 4.  now that we make it work, but might prefer 1. to 3. if what I saw is a bug.  (But, of course, prefer 3. if it is not.)

**Comment by jheer** [comment] 2017-01-14 14:27
Mea culpa! Somehow I missed that spec link entirely. If you add the following block to define width/height explicitly the problem is resolved:
```json
  "signals": [
    {
      "name": "width",
      "update": "data('layout')[0].width"
    },
    {
      "name": "height",
      "update": "data('layout')[0].height"
    }
  ],
```
(Note that in the latest parser version, the `tuples` expression function has been renamed `data` for better naming consistency.)

In addition I recommend that you add explicit padding (e.g., `"padding": 5`) to your output specs to improve the presentation a bit (and also make it more like what VL 1.0 produces).

**Closed by jheer** 2017-01-14 14:27 UTC
Labels: question
