### ISSUE TITLE
error during build, unable to find browserify-shim

### ISSUE THREAD

**Issue by mathisonian** [vega/vega#325] opened 2015-08-10 02:23 UTC
Hello,

I've been playing around with vega, and am doing some test to see how it might integrate with [lightning](http://github.com/lightning-viz/lightning).

I'm running into this error, both when trying to `require('vega')` via browserify, and when running `npm run build` in a locally cloned version of the repo. Full error output below:

```
mathisonian in ~/projects/vega on master [!]
🌜 npm run build

> vega@2.0.6 build /Users/mathisonian/projects/vega
> npm run pegjs && browserify index.js -d -s vg | exorcist vega.js.map > vega.js


> vega@2.0.6 pegjs /Users/mathisonian/projects/vega
> pegjs src/parse/events.pegjs

Error: Unable to find a browserify-shim config section in the package.json for /Users/mathisonian/projects/vega/node_modules/browserify/node_modules/browser-resolve/empty.js while parsing file: /Users/mathisonian/projects/vega/node_modules/browserify/node_modules/browser-resolve/empty.js
    at /Users/mathisonian/projects/vega/node_modules/browserify-shim/lib/resolve-shims.js:163:38
    at /Users/mathisonian/projects/vega/node_modules/browserify-shim/node_modules/mothership/index.js:27:31
    at testDir (/Users/mathisonian/projects/vega/node_modules/browserify-shim/node_modules/mothership/node_modules/find-parent-dir/index.js:20:36)
    at /Users/mathisonian/projects/vega/node_modules/browserify-shim/node_modules/mothership/node_modules/find-parent-dir/index.js:26:7
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.

> vega@2.0.6 postbuild /Users/mathisonian/projects/vega
> uglifyjs vega.js -cm > vega.min.js
```

I'm running node v0.12.4 on OSX.

**Comment by jheer** [comment] 2015-08-11 20:54
Thanks for the issue. However, I'm unable to reproduce on OSX + node v0.12.7. First `npm install` and then `npm run build` work without issue for me on a clean git clone of master. As a result, I'm closing the issue for now. Feel free to re-open should any vega-specific problems come to light.

**Closed by jheer** 2015-08-11 20:54 UTC

**Comment by mathisonian** [comment] 2015-08-11 21:19
Thanks @jheer. I just tried and was able to build successfully on another computer. I'll update this issue if I figure out what was going on in the other case.

**Comment by jimallman** [comment] 2015-10-27 23:06
@mathisonian, I've been fighting a similar error when using `watchify`. In my case, the problem file was clearly outside my project, and therefore blind to my project's `package.json`:
```
Error: Unable to find a browserify-shim config section in the package.json for /usr/local/lib/node_modules/watchify/node_modules/browser-resolve/empty.js while parsing file: /usr/local/lib/node_modules/watchify/node_modules/browser-resolve/empty.js
```
I was able to resolve this by installing watchify locally, instead of globally:
```
$ npm uninstall -g watchify
$ npm install --save-dev watchify
```
The new watchify (and its submodules) are installed within my project area, so the error does not appear.

**Comment by jimallman** [comment] 2015-10-27 23:26
I've tweaked the [Vega-and-Browserify wiki page](https://github.com/vega/vega/wiki/Vega-and-Browserify) to install `watchify` locally, to avoid the missing shim-config errors.
