### ISSUE TITLE
“orient” property for area missing from the documentation.  

### ISSUE THREAD

**Issue by kanitw** [vega/vega#333] opened 2015-08-19 01:34 UTC

**Comment by floribon** [comment] 2015-08-19 21:18
Thanks for mentioning it!

However it seems to be a property shared by `line` and `area` marks, however lines are displayed regardless of their orientation, do you know why is that different for area?

The following spec does display the line and not the area. Adding `{"orient": {"value": "horizontal"}}` to the area mark properties does display it.

I don't have any problem with that, just in case it can help you.

````
{
  "padding": "strict",
  "data": [
    {
      "name": "table",
      "values": [
        {
          "horizontal": "Q1",
          "vertical": 16
        },
        {
          "horizontal": "Q2",
          "vertical": 13
        },
        {
          "horizontal": "Q3",
          "vertical": 12
        },
        {
          "horizontal": "Q4",
          "vertical": 18
        }
      ]
    }
  ],
  "axes": [
    {
      "type": "y",
      "scale": "v",
      "grid": true,
      "layer": "back"
    },
    {
      "type": "x",
      "scale": "h",
      "grid": true,
      "layer": "back"
    }
  ],
  "marks": [
    {
      "type": "group",
      "from": {
        "data": "table",
        "transform": [
          {
            "type": "facet"
          }
        ]
      },
      "marks": [
        {
          "type": "area",
          "properties": {
            "enter": {
              "y": {
                "scale": "v",
                "field": "horizontal"
              },
              "yc": {
                "scale": "v",
                "field": "horizontal"
              },
              "x": {
                "scale": "h",
                "field": "vertical"
              },
              "x2": {
                "scale": "h",
                "value": 0
              },
              "fill": {
                "scale": "color",
                "field": "horizontal"
              }
            }
          }
        },

        {
          "type": "line",
          "properties": {
            "enter": {
              "y": {
                "scale": "v",
                "field": "horizontal"
              },
              "yc": {
                "scale": "v",
                "field": "horizontal"
              },
              "x": {
                "scale": "h",
                "field": "vertical"
              },
              "stroke": {
                "value": "steelblue"
              },
              "strokeWidth": {
                "value": 3
              }
            }
          }
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "v",
      "type": "ordinal",
      "range": "height",
      "domain": {
        "data": "table",
        "field": "horizontal"
      },
      "padding": 0,
      "points": true
    },
    {
      "name": "h",
      "type": "linear",
      "range": "width",
      "domain": {
        "data": "table",
        "field": "vertical"
      },
      "padding": 0,
      "points": true
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": [
        "rgb(166,206,227)",
        "rgb(31,120,180)",
        "rgb(178,223,138)",
        "rgb(51,160,44)",
        "rgb(251,154,153)",
        "rgb(227,26,28)",
        "rgb(253,191,111)",
        "rgb(255,127,0)",
        "rgb(202,178,214)",
        "rgb(106,61,154)",
        "rgb(255,255,153)",
        "rgb(177,89,40)"
      ],
      "domain": {
        "data": "table",
        "field": "horizontal"
      }
    }
  ]
}

````

**Comment by arvind** [comment] 2015-08-19 22:41
Huh, I didn't know we supported an `orient` property here! From my tests, it seems that `orient` is `horizontal` by default, and an area is defined by `x`, `y`, and `y2`. When `orient` is `vertical`, the area mark must instead be defined with `x`, `x2`, and `y`. (@floribon, lines are only ever defined by their `x` and `y` properties, ergo `orient` should not affect them). 

@jheer, is this the expected behaviour of area marks? If so, we should update both documentation and schema.

**Comment by jheer** [comment] 2015-08-19 22:47
This is correct. Areas are `horizontal` by default and use properties `x`, `y`, and `y2` (or `height`). You can set `orient` to `vertical` and then use `y`, `x`, and `x2` (or `width`) for layout.

**Comment by floribon** [comment] 2015-08-19 23:20
Thanks!

I also expected `height` to work instead of `y` and `y2` but this seems to create an inverted area, from the top to the `y` value:

<img width="681" alt="screen shot 2015-08-19 at 4 16 20 pm" src="https://cloud.githubusercontent.com/assets/2934743/9371919/aed559a8-468d-11e5-9afe-de37ca419c83.png">


`````
{
  "width": 500,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 28}, {"x": 2,  "y": 55},
        {"x": 3,  "y": 43}, {"x": 4,  "y": 91},
        {"x": 5,  "y": 81}, {"x": 6,  "y": 53},
        {"x": 7,  "y": 19}, {"x": 8,  "y": 87},
        {"x": 9,  "y": 52}, {"x": 10, "y": 48},
        {"x": 11, "y": 24}, {"x": 12, "y": 49},
        {"x": 13, "y": 87}, {"x": 14, "y": 66},
        {"x": 15, "y": 17}, {"x": 16, "y": 27},
        {"x": 17, "y": 68}, {"x": 18, "y": 16},
        {"x": 19, "y": 49}, {"x": 20, "y": 15}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "range": "width",
      "zero": false,
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x", "ticks": 20},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "interpolate": {"value": "monotone"},
          "x": {"scale": "x", "field": "x"},
          "height": {"scale": "y", "field": "y"},
          "fill": {"value": "steelblue"}
        }
      }
    }
  ]
}
````

Also, something different but related, the areas and lines interpolation produce an unexpected result when the chart is vertical. I wonder if you have control over this or if that's due to `d3` or anything lower level. If you do, maybe you could use this `orient` property for both lines and area to decide the way the interpolation is calculated?

<img width="1300" alt="screen shot 2015-08-19 at 4 17 55 pm" src="https://cloud.githubusercontent.com/assets/2934743/9371960/141bf240-468e-11e5-8509-4fe20f86d0fe.png">

Let me know if you want me to open new issues for these, or if that is not relevant. Thanks again for all your work, we're building a chart framework on top of vega and it works really well.

**Comment by jheer** [comment] 2015-09-12 00:03
Added the `"orient"` property to the wiki documentation, so closing this issue.

@floribon, the area behavior you note is technically correct, as you are (implicitly) leaving the y-coordinate at pixel value zero (as `y` is undefined). Keep in mind that the `height` is treated as an offset from the `y` value (nothing less, nothing more). Finally, thanks for noting the odd behavior with `monotone` interpolation. The issue does indeed appear to stem from d3's interpolator. It explicitly uses slope calculations (deltaY/deltaX), which will produce asymmetric results. We would need to transpose x and y for the interpolation to come out as desired.

**Closed by jheer** 2015-09-12 00:03 UTC
Labels: documentation

**Comment by floribon** [comment] 2015-09-12 00:17
@jheer thanks for your reply.

Any chance to have this *"We would need to transpose x and y"* as a feature request (when `orient` is set to `vertical `) even with a pretty low priority? (I understand that may not be massively awaited).

Or should I file that for Mr Bostock?
