### ISSUE TITLE
IPython Notebook issues (structure change btw Vega and Vega2?)

### ISSUE THREAD

**Issue by randyzwitch** [vega/vega#342] opened 2015-08-31 13:23 UTC
Hi folks - 

In my [Vega.jl library](https://github.com/johnmyleswhite/Vega.jl) in Julia, with Vega 1.5 I was able to successfully create my JSON objects using Julia, then have the graph display inline as a result in the IPython Notebook cell output. Once I converted over my plots to Vega 2, the plots would no longer render inside of the IPython Notebook.

Is there anything major that changed in Vega that you are aware of for this not to work? Is this what vega-embed.js is for? Any hints would be appreciated if you are familiar.

Sorry if this seems off-topic, but it's the real corner of corner cases of Julia, Jupyter and Vega all in rapid-development. :)

**Comment by jheer** [comment] 2015-08-31 15:15
There is no obvious culprit I know of. The basics of DOM manipulation and chart instantiation are not terribly different between v1.x and v2.x &mdash; and you would not need vega-embed for this (and vega-embed ultimately invokes the same parse + render routines anyway!).

It would help if you could add information that would allow others to easily replicate the issue, along with any error output from the console. Thanks!

**Comment by randyzwitch** [comment] 2015-08-31 15:50
Thanks Jeff.

In order to get the JS libraries into my Notebook, upon loading my Julia library I do the following:

```julia

#Evaluates where the Julia package is, builds file reference. Both files exist.
const d3 = Pkg.dir("Vega", "deps/d3/d3.min.js")
const vega = Pkg.dir("Vega", "deps/vega2/vega.min.js")

display("text/html", "<script>$(readall(d3))</script>")
display("text/html", "<script>$(readall(vega))</script>")

```

When I open the JavaScript console in Chrome, I can type in `d3` and get:
```d3
Object {version: "3.5.6", behavior: Object, event: null, ns: Object, time: Object…}
```

So d3 appears to be loading just fine. When I type in `vg`:

```
Uncaught ReferenceError: vg is not defined
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)(anonymous function) @ VM694:2InjectedScript._evaluateOn @ VM525:905InjectedScript._evaluateAndWrap @ VM525:838InjectedScript.evaluate @ VM525:694
```

Clicking on VM5252:694, I get:

```
with (typeof __commandLineAPI !== 'undefined' ? __commandLineAPI : { __proto__: null }) {
vg
}
```

While it might seem weird to load the JavaScript this way, it works just fine with Vega 1.5. But trying to load Vega 2 doesn't load via this method.

**Comment by domoritz** [comment] 2015-08-31 17:26
Also note that we are working on iPython notebook integration for vega-lite at https://github.com/uwdata/ipython-vega-lite

**Comment by jheer** [comment] 2015-08-31 18:28
It appears the issue is not with Vega parsing/rendering but with basic JavaScript file loading. Unfortunately, I don't have much insight into the issue.

I tested script injection on the d3js.org page (which already has d3 loaded). Entering the following lines on the console after a page load work fine for me. Both result in a valid `vg` object defined in the global scope. These also work when I replace `'head'` with `'body'`. So I suspect the problem is something particular to your setup.

```
// inject script src
d3.select('head').append('script').attr('src', 'http://vega.github.io/vega/vega.min.js');
```
```
// inject script text
d3.text('http://vega.github.io/vega/vega.min.js', function(err, text) {
  d3.select('head').append('script').text(text);
});
```

As a result, I'm closing the issue for now. Feel free to re-open if you find something that requires a change to Vega. And certainly reply with a fix when you find it!

**Closed by jheer** 2015-08-31 18:28 UTC

**Comment by randyzwitch** [comment] 2015-08-31 21:05
Thanks for looking into this @jheer. I tried with your code, and it did inject it into the page.

One thing I tried that replicates the error is inlining the JS code. For example, when I take the `<script src="http://vega.github.io/vega-editor/vendor/d3.min.js"></script>` line out and replace it with its contents (see [gist](https://gist.github.com/b3fceaeef96d06a115ae.git)), the graph renders fine.

When I do the same thing, except swap out vega.js (see [gist](https://gist.github.com/39285e801d5cfed63859.git)), the chart no longer renders.

Do I need to include more files, not just vega.js? My whole purpose in injecting the code into the Notebook, instead of using the http file reference, is so that notebooks can render without Internet access.

BTW, here is the error that occurs when you inline the vega.js code instead of using the file reference:

```JavaScript
Vega.jl%20Visualization.html:12 Uncaught SyntaxError: Invalid regular expression: /[ÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶Í·Íº-Í½Í¿Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô¯Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø -ÙŠÙ®Ù¯Ù±-Û“Û•Û¥Û¦Û®Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´ßµßºà €-à •à šà ¤à ¨à¡€-à¡˜à¢ -à¢²à¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¦€à¦…-à¦Œà¦à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œà§à§Ÿ-à§¡à§°à§±à¨…-à¨Šà¨à¨à¨“-à¨¨à¨ª-à¨°à¨²à¨³à¨µà¨¶à¨¸à¨¹à©™-à©œà©žà©²-à©´àª…-àªàª-àª‘àª“-àª¨àªª-àª°àª²àª³àªµ-àª¹àª½à«à« à«¡à¬…-à¬Œà¬à¬à¬“-à¬¨à¬ª-à¬°à¬²à¬³à¬µ-à¬¹à¬½à­œà­à­Ÿ-à­¡à­±à®ƒà®…-à®Šà®Ž-à®à®’-à®•à®™à®šà®œà®žà®Ÿà®£à®¤à®¨-à®ªà®®-à®¹à¯à°…-à°Œà°Ž-à°à°’-à°¨à°ª-à°¹à°½à±˜à±™à± à±¡à²…-à²Œà²Ž-à²à²’-à²¨à²ª-à²³à²µ-à²¹à²½à³žà³ à³¡à³±à³²à´…-à´Œà´Ž-à´à´’-à´ºà´½àµŽàµ àµ¡àµº-àµ¿à¶…-à¶–à¶š-à¶±à¶³-à¶»à¶½à·€-à·†à¸-à¸°à¸²à¸³à¹€-à¹†àºàº‚àº„àº‡àºˆàºŠàºàº”-àº—àº™-àºŸàº¡-àº£àº¥àº§àºªàº«àº­-àº°àº²àº³àº½à»€-à»„à»†à»œ-à»Ÿà¼€à½€-à½‡à½‰-à½¬à¾ˆ-à¾Œá€€-á€ªá€¿á-á•áš-áá¡á¥á¦á®-á°áµ-á‚á‚Žá‚ -áƒ…áƒ‡áƒáƒ-áƒºáƒ¼-á‰ˆá‰Š-á‰á‰-á‰–á‰˜á‰š-á‰á‰ -áŠˆáŠŠ-áŠáŠ-áŠ°áŠ²-áŠµáŠ¸-áŠ¾á‹€á‹‚-á‹…á‹ˆ-á‹–á‹˜-áŒáŒ’-áŒ•áŒ˜-ášáŽ€-áŽáŽ -á´á-á™¬á™¯-á™¿áš-áššáš -á›ªá›®-á›¸áœ€-áœŒáœŽ-áœ‘áœ -áœ±á€-á‘á -á¬á®-á°áž€-áž³áŸ—áŸœá  -á¡·á¢€-á¢¨á¢ªá¢°-á£µá¤€-á¤žá¥-á¥­á¥°-á¥´á¦€-á¦«á§-á§‡á¨€-á¨–á¨ -á©”áª§á¬…-á¬³á­…-á­‹á®ƒ-á® á®®á®¯á®º-á¯¥á°€-á°£á±-á±á±š-á±½á³©-á³¬á³®-á³±á³µá³¶á´€-á¶¿á¸€-á¼•á¼˜-á¼á¼ -á½…á½ˆ-á½á½-á½—á½™á½›á½á½Ÿ-á½½á¾€-á¾´á¾¶-á¾¼á¾¾á¿‚-á¿„á¿†-á¿Œá¿-á¿“á¿–-á¿›á¿ -á¿¬á¿²-á¿´á¿¶-á¿¼â±â¿â‚-â‚œâ„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Žâ… -â†ˆâ°€-â°®â°°-â±žâ± -â³¤â³«-â³®â³²â³³â´€-â´¥â´§â´­â´°-âµ§âµ¯â¶€-â¶–â¶ -â¶¦â¶¨-â¶®â¶°-â¶¶â¶¸-â¶¾â·€-â·†â·ˆ-â·Žâ·-â·–â·˜-â·žâ¸¯ã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ãƒ¿ã„…-ã„­ã„±-ã†Žã† -ã†ºã‡°-ã‡¿ã€-ä¶µä¸€-é¿Œê€€-ê’Œê“-ê“½ê”€-ê˜Œê˜-ê˜Ÿê˜ªê˜«ê™€-ê™®ê™¿-êšêš -ê›¯êœ—-êœŸêœ¢-êžˆêž‹-êžŽêž-êž­êž°êž±êŸ·-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¢ê¡€-ê¡³ê¢‚-ê¢³ê£²-ê£·ê£»ê¤Š-ê¤¥ê¤°-ê¥†ê¥ -ê¥¼ê¦„-ê¦²ê§ê§ -ê§¤ê§¦-ê§¯ê§º-ê§¾ê¨€-ê¨¨ê©€-ê©‚ê©„-ê©‹ê© -ê©¶ê©ºê©¾-êª¯êª±êªµêª¶êª¹-êª½ê«€ê«‚ê«›-ê«ê« -ê«ªê«²-ê«´ê¬-ê¬†ê¬‰-ê¬Žê¬‘-ê¬–ê¬ -ê¬¦ê¬¨-ê¬®ê¬°-ê­šê­œ-ê­Ÿê­¤ê­¥ê¯€-ê¯¢ê°€-íž£íž°-íŸ†íŸ‹-íŸ»ï¤€-ï©­ï©°-ï«™ï¬€-ï¬†ï¬“-ï¬—ï¬ï¬Ÿ-ï¬¨ï¬ª-ï¬¶ï¬¸-ï¬¼ï¬¾ï­€ï­ï­ƒï­„ï­†-ï®±ï¯“-ï´½ïµ-ï¶ï¶’-ï·‡ï·°-ï·»ï¹°-ï¹´ï¹¶-ï»¼ï¼¡-ï¼ºï½-ï½šï½¦-ï¾¾ï¿‚-ï¿‡ï¿Š-ï¿ï¿’-ï¿—ï¿š-ï¿œ]/: Range out of order in character class
Vega.jl%20Visualization.html:22 Uncaught ReferenceError: vg is not defined
```

**Comment by arvind** [comment] 2015-09-01 16:21
Hi @randyzwitch, this looks like some sort of character encoding issue. For example, if I copy your gist and open it in Chrome with character encoding set to utf-8 (`View > Encoding > Unicode (UTF-8)` on OS X) then the chart displays correctly.

**Comment by randyzwitch** [comment] 2015-09-03 12:46
Thanks @arvind. I've come to realize that my problems are basically summarized here:

https://github.com/mbostock/d3/pull/1921

Basically, my lack of knowledge about JS (especially requirejs), along with the fact that d3 exports a global but Vega doesn't (in keeping with the [AMD style](https://github.com/jrburke/requirejs/wiki/Updating-existing-libraries))...still don't have it working yet, but at least I know why now :)

Thanks for all your help, and the work everyone is doing on Vega 2. I can't wait to get back to building graphs again!
