### ISSUE TITLE
"Error: Operator not defined: -1" when using extent signal in bin transform

### ISSUE THREAD

**Issue by kanitw** [vega/vega#668] opened 2016-12-01 00:31 UTC
I try to apply `extent` transform before bin transform like you suggested.  However, I got a mysterious error `"Error: Operator not defined: -1"`  although I don't see any -1 in the code.

Note that if I replace `"extent": {"signal": "IMDB_Rating_extent"}` with `"extent": [0, 10]`, then the visualization renders fine without this error. 

```
{
  "autosize": "pad",
  "data": [
    {
      "name": "source",
      "url": "data/movies.json",
      "format": {"type": "json","parse": {"IMDB_Rating": "number"}},
      "transform": [
        {
          "type": "filter",
          "expr": "datum[\"IMDB_Rating\"] !== null && !isNaN(datum[\"IMDB_Rating\"])"
        },
        {
          "type": "extent",
          "field": "IMDB_Rating",
          "signal": "IMDB_Rating_extent"
        },
        {
          "type": "bin",
          "field": "IMDB_Rating",
          "as": ["bin_IMDB_Rating_start","bin_IMDB_Rating_end"],
          "maxbins": 10,
          "extent": {"signal": "IMDB_Rating_extent"}  
        }
      ]
    },
    {
      "name": "summary",
      "source": "source",
      "transform": [
        {
          "type": "aggregate",
          "groupby": [
            "bin_IMDB_Rating_start",
            "bin_IMDB_Rating_end",
            "bin_IMDB_Rating_range"
          ],
          "fields": ["*"],
          "ops": ["count"]
        }
      ]
    },
    {
      "name": "layout",
      "values": [{}],
      "transform": [
        {"type": "formula","as": "width","expr": "200"},
        {"type": "formula","as": "height","expr": "200"}
      ]
    }
  ],
  "marks": [
    {
      "name": "main",
      "type": "group",
      "from": {"data": "layout"},
      "encode": {
        "update": {
          "width": {"field": "width"},
          "height": {"field": "height"}
        }
      },
      "marks": [
        {
          "name": "marks",
          "type": "rect",
          "from": {"data": "summary"},
          "encode": {
            "update": {
              "x2": {
                "scale": "x",
                "field": "bin_IMDB_Rating_start",
                "offset": 1
              },
              "x": {"scale": "x","field": "bin_IMDB_Rating_end"},
              "y": {"scale": "y","field": "count_*"},
              "y2": {"scale": "y","value": 0},
              "fill": {"value": "#4682b4"}
            }
          }
        }
      ],
      "scales": [
        {
          "name": "x",
          "type": "linear",
          "round": true,
          "nice": true,
          "zero": false,
          "domain": {
            "data": "summary",
            "fields": ["bin_IMDB_Rating_start","bin_IMDB_Rating_end"]
          },
          "range": [0,200]
        },
        {
          "name": "y",
          "type": "linear",
          "round": true,
          "nice": true,
          "zero": true,
          "domain": {"data": "summary","field": "count_*"},
          "range": [200,0]
        }
      ],
      "axes": [
        {
          "scale": "x",
          "grid": false,
          "orient": "bottom",
          "title": "BIN(IMDB_Rating)",
          "zindex": 1,
          "encode": {
            "labels": {
              "update": {
                "angle": {"value": 270},
                "align": {"value": "right"},
                "baseline": {"value": "middle"}
              }
            }
          }
        },
        {
          "scale": "y",
          "format": "s",
          "grid": true,
          "orient": "left",
          "title": "Number of Records",
          "zindex": 0
        }
      ]
    }
  ]
}
```

**Comment by jheer** [comment] 2016-12-01 03:40
Duplicate of vega/vega-dataflow#12

As mentioned earlier, the workaround for now is to make sure the extent transform is in a different pipeline (e.g., upstream data source) from the bin transform.

**Closed by jheer** 2016-12-01 03:40 UTC
Labels: bug

**Comment by kanitw** [comment] 2016-12-01 04:00
Ah I see.  Apologies I didn't read it clearly before.  (Waking up at 5:30am to catch flight really made me pretty confused the whole yesterday ><" – sorry about that.) 

FYI, splitting data source requires some amount of restructuring for Vega-Lite, so if you plan to fix it anyway, we will fix other stuff first instead of introducing temporary structural change.
