### ISSUE TITLE
width/height do not fully determine final graph size

### ISSUE THREAD

**Issue by nyurik** [vega/vega#691] opened 2016-12-29 04:58 UTC
When backend generates a graph, it needs to know the final size of the image in order to eliminate FOUC. This is especially important if the graph image is server-side generated - the HTML would need to contain the width/height of the image, so that the browser can lay out the page even before the image gets downloaded.  The problem is that if the graph is user contributed, there is no way for the server to know the right size.   We have been using top level width/height elements, but they are not the final results - vega can unexpectedly resize based on the presence of legend, marks whose coordinates are outside of 0..width x 0..height, large number of ordinal items in a scale, etc.

I think that before Vega3 is out, we really should clean up this aspect.  Without this, we cannot reliably generate HTML, nor can we effectively support mobile devices, as they are tightly coupled with the screen sizes.

**Comment by arvind** [comment] 2016-12-29 05:16
Hi @nyurik, Vega 2 supports a [`"padding": "strict"`](https://github.com/vega/vega/wiki/Visualization) setting which should preserve the overall width/height of the visualization by resizing the data rectangle instead. In Vega 3, this logic has been moved to [an `autopad` property](https://github.com/vega/vega/blob/master/PORTING_GUIDE.md#view-layout), with `padding` saved for specifying a fixed margin around the visualization. 

Do these settings satisfy what you're looking for? If not, some more detail on what additional behavior is required would be helpful.

**Comment by nyurik** [comment] 2016-12-29 05:37
@arvind Thanks, i didn't know (forgotten?) about this feature!  Sadly, it seems badly broken on the server side:  https://www.mediawiki.org/wiki/User:Yurik/vegabugs

**Comment by nyurik** [comment] 2017-01-04 00:17
The lack of stable size and the bug in the strict mode is blocking frame/caption to the graphs, tracking at  https://phabricator.wikimedia.org/T147768

**Comment by jheer** [comment] 2017-01-04 19:56
For context, Vega v3 supports three layout mades. These are controlled via the top-level `autosize` property. The legal values are:
- `"pad"` (default) - The width/height values determine the data rectangle for plotting. Axes and legends use additional space, with extra padding added to accommodate those elements.
- `"fit"` - The width/height indicates the final size (minus any explicit padding). The data rectangle will be automatically resized to accommodate axes and legends within the given size. If elements are too large to fit in the given size, clipping may occur.
- `"none`" - No automatic adjustment of size is performed. The final size is strictly the sum of the width/height and any explicit padding.

So, for both `"fit"` and `"none"`, you should be able to compute the resulting image size as the sum of the width/height and padding. Which is preferable may depend on context. Note also that (unlike Vega 2) explicit `padding` is always added _in addition_ to the calculated size. In any case, it seems that the `"fit"` mode is exhibiting errors; I will investigate this shortly.

In addition, you can now also perform responsive layout when using SVG. We recently added the `viewBox` attribute to all generated SVGs (see vega/vega-scenegraph#5787755). This allows you to resize the SVG element and have the resulting visualization content scale accordingly.

**Comment by nyurik** [comment] 2017-01-04 20:42
Awesome, thanks @jheer for explanation.  So the difference between `fit` & `none` is that `fit` will reduce external width/height signals by auto-subtracting the size of legend & axis, right? I'm mostly thinking about the mobile/tablet usecase - if we draw a graph on mobile, and/or if mobile flips, we need to set the right width/height, and the svg and dynamic graph should resize accordingly.

**Comment by jheer** [comment] 2017-01-04 20:45
Yes, `fit` will automatically reduce the `width` and `height` signals (by subtracting axis and legend extents) so that the total size of the graphic (ignoring `padding`) matches the original width/height values defined in the specification. In contrast `none` does nothing but use the provided `width`, `height` and `padding` as-is, clipping anything that exceeds those dimensions.

**Comment by nyurik** [comment] 2017-01-04 20:50
So in `none`, if i use scale range "width", it will draw values for the whole image width minus padding. So if I add an axis or legend, they won't show up because they would (by default) be outside of the width.

**Comment by jheer** [comment] 2017-01-04 20:53
Yes, when using `none`, the axes and legends will only be visible _if_ your explicit padding is large enough to include them. In some cases users may want to explicitly control the axis and legend extents and encode this directly into the specification.

**Comment by jheer** [comment] 2017-01-04 20:55
Also, I took a look at the buggy examples at https://www.mediawiki.org/wiki/User:Yurik/vegabugs. It looks like these are using Vega 2. Can you confirm if you are seeing bugs with Vega 3, and if so, provide example specs? I have tested these features in the Vega 3 example specs and have not encountered bugs. I will check again (sometimes regressions occur!), but in the meantime if you have examples of v3 errors, please share.

**Comment by nyurik** [comment] 2017-01-04 21:00
@jheer, it will be some time before we are able to roll out Vega 3 - a lot of different systems will need to be updated, both client and server side, and I am a bit reluctant to do all that work until the code is fully released. At the same time, we already have millions of Vega 2 graphs that need to be supported, and it would be great if we can do it by injecting a small adjustment into them to control their width/height.

**Comment by jheer** [comment] 2017-01-04 21:13
OK, good to know. In that case, I'm flagging @arvind so he sees this as well. If you encounter Vega 3 issues, do let me know as well. Thanks!

**Comment by arvind** [comment] 2017-01-05 05:31
@nyurik: Can you give me the Vega JSON specs for the buggy examples displayed at https://www.mediawiki.org/wiki/User:Yurik/vegabugs. They don't appear when I click "edit source," nor do they appear to load when I click the play button.

**Comment by arvind** [comment] 2017-01-05 10:00
Thanks, and where can I find the data the specs are referring to (e.g., `Bea.gov/GDP by state.tab`)?

**Comment by arvind** [comment] 2017-01-05 10:58
Thanks! There does indeed appear to be a bug between how the dataflow graph is firing server-side vs. client-side. I'm working on fixing this issue but, in the interim, a workaround I've found is to use only the `update` property set for your marks rather than `enter`. I've verified that this produces the same rendered output server-side and client-side for the visualizations on that page.

**Comment by arvind** [comment] 2017-01-05 11:37
Fixed with 13e0bcf, and released as v2.6.4.

**Closed by arvind** 2017-01-05 11:37 UTC

**Comment by nyurik** [comment] 2017-01-05 19:54
@arvind thanks for fixing it!  I see the first two graphs are good now.  What about the third graph?  (refresh it if it doesn't show up - it has a long-running query behind it which sometimes fails). The whole graph shrinks vertically for some unknown reason.  I think that logic might need adjustments.
Also, I think Vega3 should use `fit` by default - it is by far more intuitive/expected to specify the total width/height, rather than to treat it as some value that will change depending on some internal logic.

**Comment by arvind** [comment] 2017-01-06 07:21
With ae1deef, and released as v2.6.5, Vega 2 will now recalculate the view bounds to clip the height of top-level legends. For example:

![wikipedia](https://cloud.githubusercontent.com/assets/42262/21710227/541e6428-d40d-11e6-81cc-3ff20c6b85b3.png)

To my understanding, this is [the logic](https://github.com/vega/vega-view/blob/master/src/transforms/ViewLayout.js#L71) that Vega 3 uses. The data rectangle will still be squished if legend labels are overly long, but these can be customized using a [truncate template modifier](https://github.com/vega/vega/wiki/Marks#templates) as part of customizing [legend `labels`](https://github.com/vega/vega/wiki/Legends#custom-legend-styles). Moreover, nested legends will still present a challenge for strict/fit layout calculation, particularly for Vega 2.

**Comment by nyurik** [comment] 2017-01-06 08:23
@arvind you rock! thanks!!! I will hopefully deploy it next week.

And just to make sure its not THAT easy, is there a way to dynamically figure out the width WITH the legend/axis?  For example, in [this graph](https://www.mediawiki.org/wiki/Template:Graph:Lines) that I hope will be very widely used, users need to show a title in the center of the graph. I do it with a text mark and           `"x": {"signal": "width", "mult": 0.5, "offset": 30},`. The offset is a major hack - because the legend width is not really known, i fixed it at 30 which looks okay-ish. If there is no legend, i need to remove it. If legend is too wide or too narrow, i would need to adjust it. Is there a simple way to avoid all this trouble? Or should we make an extra "graphwidth" signal, as oppose to "width" which is really a "main-graph-area-width"? Thanks!

**Comment by arvind** [comment] 2017-01-06 09:04
There is a `padding` signal available in addition to `width` and `height`. Thus, you could construct a signal like so: `{"name": "graphwidth", "expr": "width + padding.left + padding.right"}`.

**Comment by nyurik** [comment] 2017-01-06 10:25
Bleh, the signal actually has to be "width+padding.right", because the x coordinate's 0 starts after the padding. Messy but workable, thanks!

**Comment by nyurik** [comment] 2017-01-06 10:28
and i guess i cannot have an expression in the mark, i have to put it into the global signals... i really wish i had expressions everywhere :)

**Comment by jheer** [comment] 2017-01-06 14:06
With Vega 3 you do...
