### ISSUE TITLE
Regression results are different with numpy

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2198] opened 2019-11-26 22:37 UTC
I tried to compare the computation of a polynominal fit using `numpy` in Python with the new `regression` transform in Vega-lite, but the results differ:

Observe the following:

1. First using Python:
```python
import numpy as np
import pandas as pd
import altair as alt
```

```python
# load data
df = pd.read_csv('https://raw.githubusercontent.com/mattijn/datasets/master/regression_test.csv', parse_dates=[0])
```

```python
# compute 4th order polynomial 
date_numeric = pd.to_numeric(df.date)
degree = 4
poly_df = pd.DataFrame({'date': np.linspace(date_numeric.min(), date_numeric.max(), 500)})
poly_df[f'{degree}th order'] = np.poly1d(np.polyfit(date_numeric, df['value'], degree))(poly_df['date'])
poly_df.date = pd.to_datetime(poly_df.date)
```

```python
# plot the data points
points = alt.Chart(df).mark_circle().encode(
    x=alt.X('date:T'),
    y=alt.Y('value:Q', scale=alt.Scale(zero=False))
)

# plot the polynomial
polynomial_fit = alt.Chart(poly_df).mark_line(color='red').encode(
    x='date:T',
    y='4th order:Q'
)

points + polynomial_fit
```
<img src="https://user-images.githubusercontent.com/5186265/69677717-d3f53e80-10a3-11ea-9446-cb04f01daf81.png" width="500">

2. And then using the new `regression` transform using Vega-Lite:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 400,
  "height": 300,
  "data": {
    "url": "https://raw.githubusercontent.com/mattijn/datasets/master/regression_test.csv"
  },
  "layer": [
    {
      "mark": "line",
      "encoding": {
        "x": {"field": "date", "type": "temporal"},
        "y": {
          "type": "quantitative",
          "field": "value",
          "scale": {"zero": false}
        }
      }
    },
    {
      "mark": {"type": "line", "color": "red"},
      "transform": [
        {"regression": "value", "on": "date", "method": "poly", "order": 4}
      ],
      "encoding": {
        "x": {"field": "date", "type": "temporal"},
        "y": {"field": "value", "type": "quantitative"}
      }
    }
  ]
}
```

<img src="https://user-images.githubusercontent.com/5186265/69677976-85946f80-10a4-11ea-8769-5911e2542808.png" width="500">

[Editor-url](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MNIAMR9REgpG1fAYDMJs1B3o8mHKAjnWAJzEGLBMRkpN7omgzMbOyssMje8Mp4yEp4dAmopBgEjHJKpM6usXiwmeiwSd4hNN7IsLA8SgD6SeVpsBSQGgC+jpBi6ACecQYA2hoQHp7mGN4A1v4SSshq456QyQk6jErUBpNT5gAee5AAZozIYjr+BcuqUHgDhMs4kEmohNyhfj2rU5ADPZ-A5vJ4vKAAR1Y6BSzBcjCoKwOIPOl2urwo6DErDuwP+CCx4OAkAAXnFuAZTljYl08WBaciGZ5flN9msZvN3KDngttncoAkxF9-DVriyQXhQkpYKcvqhRnTiTVqDU6g1-JjsfzIMobi5tahkCxuOioJ8xID7jrvDphjhpEypgBdRz-DYm7a7dx0yDHLmoq56pJqB5g-zvT7fSDi5EAk4B02QTU4kPc8GQKEwvBw7OIx3M1ZMp0gLpAA)

Do I miss something obvious?

**Comment by jheer** [comment] 2019-11-27 08:50
Thanks for the issue! I've transferred this over to vega/vega as the error is coming from Vega's `regression` transform. The issue appears to be a case of floating point error due to the very large integer values of date timestamps. If I instead [translate the x-coordinate based on the current time](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KO3TwA1tQBO3VjIAm2KAHdEzZAqWRC6PXsYzqh0YoiQjjPS0MAWAAy+XXGRGanxDAGZ-QMhYPABPABtzHEh4ZASEi1dYEJl0BNhDAG0lCGBIPNRkqBluIwUoe2ZDCrqACgBKSABfJQBdaL10PEwcEogy0omK9CqW6VZNNIB9XyyJ10XMlPwiEnJNdCMGZjZ2VlhkJdk8ZBk8OnhuVFIMAkYJGVIhkcu8WFe6FiV1ImhoYNgOVky1usUesAo6w2kAAZtxNG9DOV4oRqqkEQ0rOhNJcsZAfniKT15FA9OlGKgzJoWvIelNuoFJhtXJVKcN0KskdMFks8SKVmtOdM8IcZLA0RjilMNqBudzIDi8SjGAlbsypWrIMgAB6EZkpNqMWAAEWGyDaP1YqCKAB1yXa3X0OmAAD4+sCW2AANXyHgdwydrvdt093oAZHGwFaAGJNW5tADUjudbopsY68cTVpDCTD2ajFHyrGQsbACaTsFTMjMmfLbsrCWrscgyomvTVfXZUtV6t5LR+AoAjELsjpReP+YKDVAZeg5QrUEq1Vzt65NS0wVpkJCeHJl8jjWSTWaWlmI6g6BSwABaMC1eoc3vIuItDvVmfqlULDcAYKSENwCQ-ue0zonS5pgN40GuECxSQJoxqSlAmg-oOu6fruI67hqcS4i0G6sAkmA0pAKEpOhAHIte8HRk6dDob4YAZm+dQ9nhva4X2-TRBgmhqIUYxTIR0xjiklFxFcqzLCJYkAcRpEpLAcSoOwEGqbEiTVEUVjcPYeCQAMvaotom44OUE4LiMgr4eqdxPHSWJflArCEFStmea43DWPAzA-rZkB-tUvh0AA7M5RHahkZIRS0q5ytYYL3NS-lQLE2hqNU5TJSkADE3jwNFAAc6AVVlu6uJeYUIPkeKXtR2rpKBtJ2rVdWQKFYDjHVO5DXux5mSkACExahno4Z4JG7ZVjW5nen6YBTY2ab2ne805uFS3dkh6rtQknXlFoOiEC0KAhGE-YjXFdXlE1SQtFBUAnZ1+2duY927gJap-YJGyPVJPKzHickKZOSnEipy5qZD9jmAj+mvWMkCljI5gWYa0iaONYDlJ9DkLdGy19D1yIotZZL2SkE7LNOj2uK5IEFZ5kDeb5RPZTEMrcPlSVLQeyAGCz6oNUTMTwM1LStR9jAdQel4S9+ZIvXi72okrp0Hj+QMg72QP3bjOWy0k4kDZJlkyVArWWfuKR4AyKOWXozzoPYHnxbrehW4NBHRqMXWOZhOvKwz3VqxMdn8g5U6EiTdGq55AN9gjsrUIZATSzk1B5NsxgeF43Tp6DtsQ29qlO1AWPIMSqkexg3t+b7HUB9lccjAnS6K5HUDJTHZTB7305tX7+tsv9xuZ2u2fFM9uT5NdwShGZHJgL4ZvIgAXlc3CGCi+SXAjzZpIYMrVuyQmWOgxrHluseWZr8uqeiSuZSkOkEM8qlaB4AAyhbLW-9NAeEvpoasCMXbqAAMI6C-nnZeRdUjBASG0dwnhECkD8F0CW5JPatzAMfAoyAEaUXYOkK2pDT6WQwMaAAosaW4SCAj0PsMw1hhN2GGlgSpHAtDyGWV3vYOkUtfBDhtnjEB1cEYfzuITTGyAURmQRgAvQwC5YpAdoaDRkDoGO0YPAxBhMl4FxXikNIOo2g3XXrg3w+CEbNy9nIQRJ9hGGkodQo+HiEYMK4YowwvDAKcJYUEnAITkT8JoX4kRYiTTBKkSqF+sidHv3ARE5Q3Bf6bnUeAzqQiYHMHRqHN2Xj0BUISMmTssBEAGM8eqbxCQADyVBNCUSujgK+jTonGLUAg3QZiYgoJaNYjBWCWAOKcfE-QiTInJOfjI7RUAoKWQUUg5RqiwEQPcWQ4peBSnfX-BQyp6Q2lXE6Q04pJihka1GVY9Bti174GmVTaYoi5kSJvhAQc3QgA) the correct fit results. I will need to investigate further to ensure an appropriate correction is applied.

**Comment by mattijn** [comment] 2019-11-27 11:00
For what it is worth, maybe also something with browsers? If I open the above linked specs in Safari the chart stays empty. Only after explicit mentioning the `"parse": {"date": "date:'%Y-%m-%d %H:%M:%S'"},` it shows the original data points. 

But then the regression computation is strange (in both Safari and Chrome):
<img width="547" alt="image" src="https://user-images.githubusercontent.com/5186265/69717755-f0799100-110c-11ea-97f8-e14dc665640e.png">

[Editor-spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KO3TwA1tQBO3VjIAm2KAHdEzZAqWRC6PXsYzqh0YoiQjjPS0MAWAAy+XXGRGanxDAGZ-QMhYPABPABtzHEh4ZASEi1c9dDxMHABtJQhQCDKoGXRUZKhpVk00gH1fLPKoesyU-CISck10IwZmNnZWWGQG2TxkGTw6eG5UUgwCRgkZUhy88bxYZfRYidJNGhPYWB4ZRunY+dgKVvLIADNuTRXDUrbXeMIa1PujzaVnQmnGn0gW3+UKwAHIAKQATQAtPDUKi9GB4QAJLDwgCyeIAyrDIABfQLfSHpRioMyaQwKSDFMpklkUllfJ6VaqMrboZpA1x1Br-EVNFqUsqQPD9GSwV7vQxFb4lFlU37-E5aZDnS5C4EADz5uXMUqpcUZFHQCVYZvVwOqLG4BhShG4CUt5uBbz0Ex83qeB2VkNNCig1tt5gAug6IGzvrHygmwNHohhNGpYMrOQ7IDz-gl0HEJs1GhmswaZXE-oyEvZ7VTYokagVIPWZDHvTE3ngIc9GOlXVAtqxUAUADqh6ZT6Pk7vPbSoCH8xni5CCjlUmYLP2fOPtQhQ-eq6WxbRqGrASCRu2MgDE3ngAHYABzoV-zg+uY04a8IG1-mNeQoAHIcTWmL9T1cS0-xieBAMZL1QMHBJhxvG07y3aDqQHTthy5HCLmoSpOigRhYAANRtDwAApR3HKcoVnABKMAADJ2LACiADF7DMWiAGoGMnadkFYjiuIo6j6z0ejcjHUTb3EyBozYzjuNgPiZAE4SFMYjCo1Y5loLAFNvnM1l2SlQjXALOti1LABGctQUrbtNTrBsq2bJIQw7Ls82kTQ+zgsC0IgxSmNNWcoOBRdFhXXJ8hHZLN27HcXSvA9IFYI8wz-b9allbhLwhZTGROAxsNPSBfzAf8EL8lJgJQ8CUmPGrVUgWCGvgxCUmQl5UPQiquqpP08OQAiiuFEJSMZaSaLkkTopnVT1KkrT+OmITVrEiSNKW2T5LwKLDLtQ6tu03T9uU4yiss5MHUslM00sACkmzQpcypeyWqrTyUjwWlG2BPRFnQewT268K9G+sAVWg69VxSddBRA4b2tSyDxraFHkoggVJTaiKOrDJ6yiTNo8cgOVqFbAI+uIhaUncTxEHJan4xsvN-qgL08yBqAAtBKsIYwaHCtquGEaR08CbyNcdFFDHSdGzDzDx8pFZS6difDLGyYjTXyQPbnWW7enW3-eabUZFAQjCCkwF8d6qQALwmbhDGeG1xm7HS0kMWU7XZJR3agdBDV1HMdaCpqgKrN5B1mRl2G4AhEu7LQPCJROkKrXPh1D5APMYdQAGEdDTuCWftlI0kYBJaPZlhSD8Fi4qeCWobkHA-YSAO8yLdh0gRwfh6pDBDQAUUNaZa9d7s6RkefF9C5ehYrysB-9su8w9+w-Xq3xrN+4FPv+QWqRTmZN-bZBnj7HPNDzguAdfjwQ80O1y6rmum9bYkQblAJuLdHahDwB3XwXdaa9ylmASeB8qSj3Hr7feK9o7r3voYAIeZV44KXvgjUO8J6YMPsfZAp9z7xybB-KAwE8x3yXpADOWdlxf2HMg8ueBmo4zBk8NBCQeK2lgJzHApduzCIAPJUE0EWQgP8-7bwAboIBMQ7ZkVSMEFubdEAwLgd2I++hqF4NoWUWytQGE9WTm-XBKQkjPyLm-bhFDSF8P+BVaR6Ax4JDkRMRRyiUHAhBmopewDWZgN0bRSB+BDHd2lCYk+5jnoQFjGSIAA)

**Comment by jheer** [comment] 2019-11-27 12:35
Thanks again @mattijn. In your latest example there are multiple issue interacting. The first is that browsers don't support date parsing in a consistent way. This is a known issue and it is recommended that users provide proper date formats as needed. The second issue is that it appears string concatenation is occurring in the date field, which would arise due to addition coercing to string rather than number when a Date is involved. I will update the regression logic to ensure proper number coercion.

**Comment by jheer** [comment] 2019-11-28 15:33
PR #2202 updates the regression methods in vega-statistics for improved numerical stability, and fixes the number coercion bug noted above. Linear (or transformed linear) regression methods now use online average calculations rather than sum-then-divide. The other methods (loess, quad, poly) now operate on mean-centered coordinates and then transform predictions and fitted coefficients back to the non-mean-centered space.

I've noted that the results are different from the numpy examples shared by @mattijn above. It looks like those methods also suffer from numerical issues... the 4th order polynomial example from numpy above appears to actually be a "degenerate" 2nd order (quadratic) fit.

(@HarryStevens: you might also be interested in these issues for the d3-regression library.)

**Closed** 2019-11-29 09:42 UTC
Labels: bug

**Comment by HarryStevens** [comment] 2019-12-05 08:30
@jheer Thank you for alerting me to this issue. I was not able to reproduce the bug using d3-regression, as you can see in [this notebook](https://observablehq.com/d/dcea42731194a6bf). However, I will look into implementing your improvements, as "numerical stability" certainly seems like a worthwhile goal.

Incidentally, as I was just now looking at the source code for regressionPoly, I realized that I was not exporting the predict function, so I patched that. I don't know when I would have discovered that issue if I hadn't looked into this one, so doubly thank you.

**Comment by mattijn** [comment] 2020-02-01 19:29
I'm confused. Now the above used example doesn't give any regression line anymore for fits other than linear..:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 400,
  "height": 300,
  "data": {
    "url": "https://raw.githubusercontent.com/mattijn/datasets/master/regression_test.csv",
      "format": {
        "type": "csv",
        "parse": {"date": "date:'%Y-%m-%d %H:%M:%S'"}
      }    
  },
  "layer": [
    {
      "mark": "line",
      "encoding": {
        "x": {"field": "date", "type": "temporal"},
        "y": {
          "type": "quantitative",
          "field": "value",
          "scale": {"zero": false}
        }
      }
    },
    {
      "mark": {"type": "line", "color": "red"},
      "transform": [
        {"regression": "value", "on": "date", "method": "poly", "order": 4}
      ],
      "encoding": {
        "x": {"field": "date", "type": "temporal"},
        "y": {"field": "value", "type": "quantitative"}
      }
    }
  ]
}
```
<img width="797" alt="image" src="https://user-images.githubusercontent.com/5186265/73597863-1ec28500-4531-11ea-9fb2-6a13d6cbbed5.png">

[Editor-url](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MNIAMR9REgpG1fAYDMJs1B3o8mHKAjnWAJzEGLBMRkpN7omgzMbOyssMje8Mp4yEp4dAmopBgEjHJKpM6usXiwmeiwSd4hNN7IsLA8SgD6SeVpsBRqGp5QAGbc3lkGHt2ekHgAnoTI-vDtnSOjhOjesUOQBdM46y7IWADkAKQAmiIHqKc6YAcAElgHALJ3AMp7kAC+XZ5v3RpvjpBidDjOIGADan2G3UgGG8AGt-BIlNNHFDkgkdIwlNQhp8oQAPNY9RjIMQ6fwbNRQCZTfxJVCEfroPx-XGjcY4hZQ6mbKAAR1Y6BSzBcjCo8055iJJLJWwoTNYyNZUIQTJ5wEgAC84twDD0mbEPhLDSNjRAWd1IaMYfD3GNJjyAZjkVAEmJ+v4amTzSMxqElLA+gMwUqwOqatQanUGv45WIFZTIMpyTsE6hkCxuDKoAyxOzVFB+joQThpKbPABdFGjNGZzHY9whyAE21S0nJpIJ7m0tAM0LMqtQ9kt4lt2Xy512mlbfmCvDCudistmz7G8sgN5AA)
