### ISSUE TITLE
Error constructing node-canvas after import

### ISSUE THREAD

**Issue by topher** [vega/vega#831] opened 2017-05-29 01:07 UTC
While importing vega in to a react native project, I receive for an error after importing vega into the project. 

### Steps to reproduce
1. npm install react-native
2. react-native init vega-rn-test
3. cd vega-rn-test
4. npm install --save vega
5. Import vega to project in `vega-rn-test/index.ios.js`

```
import React, { Component } from 'react';
import { AppRegistry, View } from 'react-native';
import vega from 'vega';

export default class vega-rn-test extends Component {
  render() {
    return <View /> ;
  }
}

AppRegistry.registerComponent('vega-rn-test', () => vega-rn-test); 
```
6. react-native start
7. react-native run-ios

### Expected Result
Successful ios build,  successful render of blank react-native view component 

### Actual Result 
Successful ios build, with react-native error
![screen shot 2017-05-28 at 5 38 42 pm](https://cloud.githubusercontent.com/assets/20007602/26533478/59a5ff2e-43ce-11e7-9928-ca46afb54bc5.png)

top of call stack references the method in `vega.js`
```
try { Canvas = require('canvas'); } catch (e) { Canvas = null; }

function Canvas$1(w, h) {
  var canvas = domCreate(null, 'canvas');
  if (canvas) {
    canvas.width = w;
    canvas.height = h;
  } else if (Canvas) {
    canvas = new Canvas(w, h);
  }
  return canvas;
}
```

### Environment 
"vega": "^3.0.0-beta.32"
"react": "16.0.0-alpha.6",
"react-native": "0.44.2",

**Comment by jheer** [comment] 2017-05-29 21:26
Thanks @topher!

I just pushed a new version of vega-scenegraph (v2.0.0-beta.30) that _should_ fix this, but I don't have a react-native setup in which to test. Can you see if the problem is resolved? You'll need to make sure that the latest vega-scenegraph version is in the `node_modules` folder of a local clone of the `vega` repository, and then make your own Vega build (`npm run build`).

**Comment by jheer** [comment] 2017-07-11 16:27
@topher, any update on this? Does it work for you now? I'd like to close out this issue if so.

**Comment by wiibaa** [comment] 2024-02-21 08:25
vega-scenegraph is now 4.11.2 and its README as a clear warning about node-canvas. I would be in favor of closing this.

**Closed** 2024-02-21 10:45 UTC
Labels: bug
