### ISSUE TITLE
Streaming data API trouble

### ISSUE THREAD

**Issue by rbishop-bah** [vega/vega#310] opened 2015-07-27 17:39 UTC
I'm having major problems using the new streaming data API.  Specifically the view.data() function seems to be updating the values of the wrong property.  I'm seeing this both when updating one data set at a time and in batch mode.  

It's of course possible that I'm doing something wrong.  Consider this a placeholder or a chance to add some additional streaming data testing until I can narrow it down further and/or work up a small example that demonstrates the problem.  I figured it'd be best to create the issue early as it is blocking me from using Vega 2 and I imagine it would block many others as well.

**Comment by arvind** [comment] 2015-07-27 18:11
Thanks for filing the issue, Rob. An example that demonstrates the behaviour you're experiencing would be helpful. It is indeed an area that we need to add some unit tests for, but I've been using the streaming functionality across other areas of Vega (e.g., in the benchmarks) and not noticed any issues so far. 

For example, with the [bar](http://vega.github.io/vega-editor/?spec=bar) example online, if we were to move properties from `enter` to `update`, the following correctly doubles the height of even bars. 

```js
ved.view.data('table').update(function(d) { return d.x % 2 === 0; }, 'y', function(d) { return d.y*2; });
ved.view.update();
```

**Comment by rbishop-bah** [comment] 2015-07-28 03:09
Looks like it was an issue in our code coupled with some internal errors thrown by Vega during update/rendering that I'm still researching.  I'll report them separately if need be.

**Comment by ajturner** [comment] 2015-07-31 01:49
I'm seeing an issue as well where the graphics are not updating, but the axes/scales are. So @arvind your example appears to work, but only because the bars relative values don't change.

This shows the errors:

```javascript
ved.view.data('table').update(function(d) { return true; }, 
  'y', function(d) { return 100*Math.random(); });
ved.view.update();
```

Similarly there is an issue with adding features:

```javascript
ved.view.data('table').insert({"x":21, "y": 50});
ved.view.update();
// Error in DataSource:37: TypeError: tuples.map is not a function
```

**Comment by ajturner** [comment] 2015-07-31 01:54
_updated my comment that fixed the insert example code but still shows an error_

**Comment by arvind** [comment] 2015-07-31 01:54
@ajturner, your first code example works for me with the online editor. **Note**: The bars do not update with the example spec as-is. At a minimum, the `y` and `y2` properties must be copied/moved to the `update` property set. 

With your second example, `insert` expects an array of values. The following works once `x` and `width` are copied/moved to `update` as well. 

```js
ved.view.data('table').insert([{"x":21, "y": 50}]);
ved.view.update();
```

Vega should probably take care of this second case for you, however.

**Comment by ajturner** [comment] 2015-07-31 01:59
@arvind I'm not sure I understand what you mean that it works for you, but that the bars don't update. 

I fixed my example with the `insert` but it exhibits a similar bug where the new marks are added but the old marks are not updated.

![updatevega](https://cloud.githubusercontent.com/assets/1218/8999297/2e8af80c-3706-11e5-9ae5-fb4af1e57123.gif)

**Comment by arvind** [comment] 2015-07-31 02:02
Thanks for including the GIF, I was just about to do the same :) Try it with the following spec for the rect marks:

```json
    {
      "type": "rect",
      "from": {"data": "table"},
      "properties": {
        "enter": {
        },
        "update": {
          "x": {"scale": "x", "field": "x"},
          "width": {"scale": "x", "band": true, "offset": -1},
          "y": {"scale": "y", "field": "y"},
          "y2": {"scale": "y", "value": 0},
          "fill": {"value": "steelblue"}
        },
        "hover": {
          "fill": {"value": "red"}
        }
      }
    }
```

You'll notice that I've moved the spatial properties from the `enter` property set to the `update`. As you may recall, `enter` properties are executed _only_ for new data. Update is run for new+existing data. With the spec in your GIF, only new rectangles are ever positioned. See Mike Bostock's [Thinking with Joins](http://bost.ocks.org/mike/join/) tutorial for more information about enter, update, and exit.

**Comment by ajturner** [comment] 2015-07-31 02:32
brilliant! of course makes sense now. hopefully that helps @rbishop-bah too.

![dynamic](https://cloud.githubusercontent.com/assets/1218/8999609/e94c1f96-370a-11e5-851b-323595b0528f.gif)

**Comment by rbishop-bah** [comment] 2015-07-31 11:10
@ajturner Thanks.  Unfortunately I continue to see problems related to data updates, but as I mentioned above not due to the initial problem I reported.  Nor are they due to not using `update` rather than `enter`.

I described some of the things I'm seeing in this post:
https://groups.google.com/forum/?hl=en&fromgroups#!topic/vega-js/ABYI5rYDhok

In a nutshell I have working (complex) specs that can render their data statically, but when I do a remove/insert cycle with the same data (with changed values) Vega blows up on me.  One of the things I'm seeing is value arrays having wrong lengths with values doubled up (in other words a remove/insert is acting like an insert only).  Some of our visualizations have rapid-fire data updates and rendering.  I'm wondering if there isn't some kind of race condition when multiple data updates come in during a single animation cycle.

**Comment by arvind** [comment] 2015-08-03 21:55
@rbishop-bah, d87e205 should fix the issue you were seeing with keyed marks -- there should indeed be continuity between removals/inserts for mark instances that share the same key. Let us know if that resolves your issues. 

If not, more information (particularly steps to reproduce the behaviour, preferably with minimal specs) would be helpful to track down the issues. Thanks!

**Comment by rbishop-bah** [comment] 2015-08-04 11:41
Ah, very good!  Will there be a 2.0.7 or 2.1 release soon?  I'll give everything another try and report back after the release.

**Comment by arvind** [comment] 2015-09-08 19:54
Hi @rbishop-bah, I wanted to follow-up to see if subsequent releases resolved the issues you were experiencing? If not, could you provide more info to help us narrow down the problem? Thanks!

**Comment by rbishop-bah** [comment] 2015-09-08 21:23
Soonest I can get to this is late Sep.

**Comment by arvind** [comment] 2015-11-06 19:22
Hi @rbishop-bah, I'm going to go ahead and close this issue out. If you're still experiencing issues, please re-open the issue, or start a conversation on the [vega-js google group](https://groups.google.com/forum/#!forum/vega-js). Thanks!

**Closed by arvind** 2015-11-06 19:22 UTC
Labels: question
