### ISSUE TITLE
Enable serialization of state data

### ISSUE THREAD

**Issue by marcprux** [vega/vega#2947] opened 2020-10-26 14:14 UTC
We would like to be able to serialize and store the the vega `view.data`. In the "Simple Bar Chart" example, we can get a list of all the rendered data with:

```js
Object.keys(VEGA_DEBUG.view.getState({ data: (name, ds) => true }).data); // ["root", "source_0", "data_0", "marks"]
```

Some of this data is serializable:

```js
> JSON.stringify(VEGA_DEBUG.view.data("data_0"));
< "[{\"a\":\"A\",\"b\":28},{\"a\":\"B\",\"b\":55},{\"a\":\"C\",\"b\":43},{\"a\":\"D\",\"b\":91},{\"a\":\"E\",\"b\":81},{\"a\":\"F\",\"b\":53},{\"a\":\"G\",\"b\":19},{\"a\":\"H\",\"b\":87},{\"a\":\"I\",\"b\":52}]"
```

But others are not:

```js
> JSON.stringify(VEGA_DEBUG.view.data("root"));
< TypeError: JSON.stringify cannot serialize cyclic structures.
```

We currently work around this by simply catching the exception and skipping that data set, but it would be nicer if the data could actually be exported to a serializable form somehow. Lacking that, it would be nice to be able to obtain a filtered list of serializable data keys that we can use without wasting the effort of trying and catching the `JSON.stringify` failures.

This may be related to https://github.com/vega/vega/issues/1730, but note that we only need the `data` to be serializable (not the entire state).

**Comment by domoritz** [comment] 2020-10-26 15:06
Duplicate of #1730

**Closed by domoritz** 2020-10-26 15:06 UTC
Labels: feature-request

**Comment by marcprux** [comment] 2020-10-26 20:40
Is there some rhyme or reason behind why some of the results of `view.data(key)` are serializable, and others are not? I'm concerned that what is be serializable today may, in a future, become unserializable due to the introduction of cyclic structures.

**Comment by domoritz** [comment] 2020-10-26 20:44
We do not guarantee JSON-serializability so I recommend that you don't rely on it right now.

**Comment by jheer** [comment] 2020-10-27 07:48
We can not guarantee this now or in the future, as user-provided data may include cyclic references. In addition, the `root` signal points to the scenegraph root, and scenegraph elements involve cyclic structures... BUT the scenegraph also includes its own serialization utilities and we don't typically want to include the scenegraph as part of the state snapshot (as we should be able to regenerate it from the rest of the state).
