### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Hammond2789** [vega/vega#2306] opened 2020-01-14 15:54 UTC
./node_modules/vega-embed/build/src/embed.js
Module not found: Can't resolve 'vega-lite' in 'E:\polymerui\polymerui\node_modules\vega-embed\build\src'

In my dependencies
"react-vega": "^7.1.1",
"vega": "^5.9.1",
"vega-lite": "^4.0.2",

**Comment by jheer** [comment] 2020-01-14 16:02
This appears to be a problem with vega-embed? Vega itself (this repo) does not use or depend on vega-embed. Feel free to include more context and details in your issue report if you believe this is a problem with vega proper.

**Comment by domoritz** [comment] 2020-01-14 17:25
Duplicate of https://github.com/vega/react-vega/issues/82

**Closed by domoritz** 2020-01-14 17:25 UTC
