### ISSUE TITLE
Allow group references in axis & legend properties

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#164] opened 2013-12-15 17:05 UTC
It would be handy to be able to reference group properties like width & height from within axis and legend properties, so that things like titles and tick lengths could be set relative to the size of the spec (or enclosing group). E.g.:

```json
  "axes": [
    {
      "type": "x", 
      "scale": "x",
      "title": "X Axis",
      "properties": {
        "title": {
          "fontSize": { "group": "width", "mult": 0.2 }
        }
      }
    }
  ],
```

**Comment by arvind** [comment] 2015-07-09 21:41
Duplicate of #151 which is resolved in Vega 2.0.

**Closed by arvind** 2015-07-09 21:41 UTC
Labels: feature-request
