### ISSUE TITLE
domainMid of diverging color scheme ignored when it falls outside data range

### ISSUE THREAD

**Issue by sacundim** [vega/vega#2656] opened 2020-05-27 05:12 UTC
(See also: https://github.com/vega/vega-lite/issues/6544)

I've made a chart that uses a diverging color scheme with `"domainMid": 0` with the expectation that this would render negative numbers with the lower half of the color scheme and positive ones with the upper half.  But when the data contains only positive numbers, Vega warns in the console that `domainMid` falls outside of the domain:

```
WARN Scale domainMid exceeds domain min or max. 0
```
...and proceeds to map positive numbers to the whole domain, and in a very coarse fashion that only seems to use the extreme colors from the range, as illustrated by this example (which I've tried to simplify as much as I could):

![Reproduction](https://user-images.githubusercontent.com/4076056/82979523-1ab4ea00-9f9c-11ea-9f32-88e650a6b315.png)

* [Reproduction](https://vega.github.io/editor/#/gist/3aa91dcdb559ae8d315f6d23f48ec73e/Reproduction.json)

When I add a -1 value to the data set, it renders just perfect:

![Add-negative-one](https://user-images.githubusercontent.com/4076056/82979764-bc3c3b80-9f9c-11ea-9483-4b9025399bb8.png)

* [Same spec, but data has a negative one]( https://vega.github.io/editor/#/gist/3aa91dcdb559ae8d315f6d23f48ec73e/Add-negative-one.json)

When I filed [a ticket on this against Vega-Lite](https://github.com/vega/vega-lite/issues/6544), @domoritz offered a workaround on Vega-Lite that compiles to a Vega spec similar to this one, with a `domain` to which `[0]` has been added:

* [Domain union with zero](https://vega.github.io/editor/#/gist/3aa91dcdb559ae8d315f6d23f48ec73e/Domain-union-with-zero.json)

![Domain-union-with-zero](https://user-images.githubusercontent.com/4076056/82979958-2b199480-9f9d-11ea-9cbc-8d2c13ce6a94.png)

**Comment by domoritz** [comment] 2020-05-27 06:07
Thank you for filing the issue. 

@jheer I think the problem is best fixed in Vega (if at all) so the behavior is consistent across tools but if you disagree, we can see how we can address it in Vega-Lite instead.

**Comment by jheer** [comment] 2020-05-27 13:32
Hmm... I think we should still raise a warning regardless. However, instead of then ignoring `domainMid` I suppose we could add it as a new extremum (either min or max) depending on the value. I believe that would correspond to the output for the union example above. Thoughts?

**Comment by domoritz** [comment] 2020-05-27 15:41
Adding a new min/max sounds good to me.

**Comment by sacundim** [comment] 2020-05-27 16:59
Well, as a longtime skeptic of warning log messages, I'll offer this contrary take: what purpose is the warning supposed to serve?  In this case, for example, my Vega-Lite original example would render as I expect it to, but I (and any visitor to the site) would get "warned" about it... and then what?

I'm also just having flashbacks to all the countless times throughout the years where I've had users file reports where they list me piles and pails of warning log messages logged in the vicinity (or not) of what's actually a silent failure, because how are they supposed to know? And training client services on which warnings they should ignore (nearly all of them, nearly all of the time)...

So I'm aware that my take here is almost certainly noobish and parochial, but I'd say there's a choice to be made here between:

* The `domain` field's semantics is it's a literal, final statement of what the scale's domain is. Then a spec that says `"domainMid": 0` but specifies a domain that might not span zero is just wrong—a contradiction. Ideally it would merit an error, but a warning would then be justifiable measure to not break older specs, and the badly rendered output would be acceptable. The advantage of this approach as I see it is that the semantics of the specs are more transparent—it's more "do what I say" and what `domain` says is the final word.
* The `domain` field is one of multiple items that are taken into consideration to decide what the scale's actual domain is, and `domainMid` is another such item. The best argument I can think of for this one is that it's odd that Vega would use the values in my data to infer the endpoints of my domain at runtime, but not use the `domainMid` in the spec similarly in this inference process.

/rant 😀

**Comment by jheer** [comment] 2020-05-29 07:28
I've added logic to include domainMid as the new min or max if it exceeds the existing domain. However, I'm keeping the warning, rant above notwithstanding. :) The warnings are useful to help users catch errors, particularly within interactive contexts such as Jupyter/Altair or Observable. Production deployments can (and probably should) adjust the logLevel or use a custom logger to prevent end users from seeing internal messages.

**Closed** 2020-06-02 09:47 UTC
Labels: discussion, enhancement

**Comment by sacundim** [comment] 2020-06-02 10:00
Thanks guys!
