### ISSUE TITLE
5.12.1 breaks interactive legend

### ISSUE THREAD

**Issue by jakevdp** [vega/vega#2641] opened 2020-05-21 16:16 UTC
The following produces a chart without a working interactive legend:
```html
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega@5.12.1"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega-lite@4.8.1"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
</head>
<body>
  <div id="vis"></div>
  <script>
      var spec = {"config": {"view": {"continuousWidth": 400, "continuousHeight": 300}}, "data": {"url": "https://vega.github.io/vega-datasets/data/unemployment-across-industries.json"}, "mark": "area", "encoding": {"color": {"type": "nominal", "field": "series", "scale": {"scheme": "category20b"}}, "opacity": {"condition": {"value": 1, "selection": "selector002"}, "value": 0.2}, "x": {"type": "temporal", "axis": {"domain": false, "format": "%Y", "tickSize": 0}, "field": "date", "timeUnit": "yearmonth"}, "y": {"type": "quantitative", "aggregate": "sum", "axis": null, "field": "count", "stack": "center"}}, "selection": {"selector002": {"type": "multi", "fields": ["series"], "bind": "legend"}}, "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json"};
      var embedOpt = {"mode": "vega-lite"};
      vegaEmbed("#vis", spec, embedOpt)
  </script>
</body>
</html>
```
Changing ``5.12.1`` to ``5.12.0`` fixes the issue.

**Comment by domoritz** [comment] 2020-05-21 16:21
This could be an Vega-Embed issue. Let's track the issue in https://github.com/vega/vega-embed/issues/448.

**Comment by domoritz** [comment] 2020-05-21 16:22
Actually, I thought the issue was embed since it's working in the editor but the editor uses 5.12.0.

**Comment by domoritz** [comment] 2020-05-21 16:27
I suspect the issue is https://github.com/vega/vega/commit/e47a48f0b1a5669c99577d0196f27179f443b5ef

**Comment by domoritz** [comment] 2020-05-21 16:28
Switching to SVG is a workaround: https://bl.ocks.org/domoritz/bbd2cc22e8b1fe2eb25c378d34992d65/50b618ed42f3e9bfa68cff7f98c3f469a524f817

**Comment by jheer** [comment] 2020-05-21 16:43
Thank you for catching this. Fortunately this should be an easy fix. Will try to push a patch release within the next day.

**Comment by firasm** [comment] 2020-05-22 02:16
Thanks @jheer ! I know this will be fixed very soon, but in the meantime one of my students was hoping to have this for a presentation soon, what's the best way to use 5.12.0 ?

I know if an `Altair` plot is saved to html, I can just change replace 5.12.1 with 5.12.0 in the following line:

`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega@5.12.1"></script>`

But what's the best way to downgrade the Vega version when using Altair in a jupyter notebook?

I tried `npm install vega@5.11.1` locally but that doesn't seem to me impact the version of Vega being used. Is it perhaps Vega-embed or Vega-lite whose version I need to downgrade using `npm`?

**Comment by jakevdp** [comment] 2020-05-22 03:31
Add a snippet like this to the top of your notebook to specify library versions you want to use:
```python
import altair as alt
from altair.utils.display import HTMLRenderer
alt.renderers.register('my_renderer', HTMLRenderer(
    mode="vega-lite",
    template="universal",
    vega_version='5.10.0',
    vegaembed_version=alt.VEGAEMBED_VERSION,
    vegalite_version=alt.VEGALITE_VERSION,
))
alt.renderers.enable('my_renderer')
```

**Closed** 2020-05-22 06:46 UTC
Labels: bug

**Comment by jheer** [comment] 2020-05-22 07:01
Update: v5.12.2 has been released with a fix for this issue.

**Comment by loxs** [comment] 2020-06-01 07:01
Click events still don't work, though others (eg. mouseover) do work with the new version 5.12.3

```
      vegaEmbed(viewElement.current, compileSpec(), { actions: isAdmin, renderer: 'svg' }).then(
        ({ view: createdView }) => {
          if (mounted) {
              createdView.addEventListener('click', () => console.log('click'));
              createdView.addEventListener('mouseover', () => console.log('mouseover'));
              setView(createdView);
          }
        }
      );
```

Switching to svg renderer is a workaround indeed (clicks work then).

**Comment by jheer** [comment] 2020-06-01 13:42
@loxs, thanks for posting. However, I can not replicate the problem: v5.12.3 works fine for me using the exact code included below. Perhaps you need to clear your browser cache? (You might try opening the developer console and entering `vega.version` to double check which version is actually loaded.)

```html
<head>
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@4"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
</head>
<body>
  <div id="view"></div>
  <script>
    var view;
    vegaEmbed(
      '#view',
      'https://vega.github.io/vega/examples/bar-chart.vg.json',
      { renderer: 'canvas' }
    ).then(result => {
      view = result.view;
      view.addEventListener('click', () => console.log('click'));
      view.addEventListener('mouseover', () => console.log('mouseover'));
    });
  </script>
</body>
```

**Comment by loxs** [comment] 2020-06-02 06:34
@jheer hmm, true, your version works fine... it has to be something in my toolchain, probably some of the many vega packages that hasn't been upgraded, I'll investigate and report back.

**Comment by loxs** [comment] 2020-06-02 07:10
I had to nuke and rebuild my yarn.lock file, but after all, indeed, the regression is fixed.

**Comment by bmorris3** [comment] 2022-04-22 14:57
Hi @jakevdp I'm seeing a similar error again, where I'm trying to replicate [this docs example](https://altair-viz.github.io/gallery/scatter_href.html), but I find that clicking points doesn't trigger the href'ed link. My example figure is hosted [here](https://owls.readthedocs.io/en/latest/owls/sindices.html) and the peculiar thing is that the SVG version works (opens link on click), as was reported earlier. I tried using a newer version of vega with https://github.com/vega/vega/issues/2641#issuecomment-632459205 but it didn't help. Any tips?
