### ISSUE TITLE
Memory leaks with long-running streaming data apps

### ISSUE THREAD

**Issue by ccra79** [vega/vega#675] opened 2016-12-07 09:35 UTC
Hi,

I am using the Vega chart to display a line chart live updates( around 10 new points a second, around 200 point at a time).
After a few hours browser (Chrome 54) memory increased from 30 MB to 500MB and finally crashed.
This will happens with latest stable 2.5.3 and also with beta version 3.0. beta 7. This issue is not on the older version like 1.5.4

**Here is the chart configuration:**
`
var options = {
            "width": window.width,
            "height": window.height,
            "padding": {"top": 10, "left": 40, "bottom": 30, "right": 10},
            "data": [
                {
                    "name": "table",
                    "values":  window.items
                }
            ],
            "scales": [
                {
                    "name": "x",
                    "range": "width",
                    "domain": {"data": "table", "field": "date"},
                    "zero": false
                },
                {
                    "name": "y",
                    "range": "height",
                    "domain": {"data": "table", "field": "value"},
                    "nice": true,
                    "clamp": true,
                    "zero": false
                }
            ],
            "axes": [
                {"type": "x", "scale": "x",  "offset": 5, "ticks": 5},
                {"type": "y", "scale": "y"}
            ],
            "marks": [
                {
                    "type": "line",
                    "from": {"data": "table"},
                    "properties": {
                        "enter": {
                            "x": {"scale": "x", "field": "date"},
                            "y": {"scale": "y", "field": "value"},
                            "y2": {"scale": "y", "value": 0},
                            "stroke": {"value": "steelblue"}
                        },
                        "update": {
                            "x": {"scale": "x", "field": "date"},
                            "y": {"scale": "y", "field": "value"},
                            "y2": {"scale": "y", "value": 0},
                            "fillOpacity": {"value": 1}
                        }
                    }
                }
            ]
        };
`

        vg.parse.spec(options, function (chart) {
            window.chart = chart;
            window.view = chart({el: "#viz", renderer: "canvas"});       
            window.view.update();
        });`

window.items array is a 200 items array with an item like this:

[date: 0, value: 4311.26871]
[date: 1, value: 2311.26871]
..
[date: 199, value: 5311.26871]

**Here is the update function:**
`window.items.push({"date": window.count++, "value": arrRecords[idx]});

window.items.shift();

window.view.data("table").remove(function(d) { return true; });
window.view.data("table").insert(window.items);
window.view.update();`

As you see I first remove the old data and then i add an updated version of window.items array with the 200 items.

Can you tell us whey the old data is still remained in the chart and the memory issue appears?

Thank you very much!

**Comment by jheer** [comment] 2016-12-07 17:03
Thanks for the issue and example. This is a known problem we intend to fix prior to the official Vega 3.0 release. The crux of the issue is that some of the data flow operators maintain internal state that requires periodic garbage collection for long-running streaming data applications.

**Comment by jheer** [comment] 2016-12-22 18:32
This issue is addressed in v3.0.0-beta.10 (for all mark types _except_ group marks, see #688). Filters, tuple indices and data joins now perform periodic garbage collection to prevent memory bloat. I've added a simple streaming data test to the web examples (`web/stream.html`) and can confirm a steady heap profile size for long running sessions.

By default, cleaning occurs once there are  10,000 (`1e4`) unused entries in the backing maps. To perform cleaning more aggressively (e.g., for smaller data sets), set the `view.cleanThreshold` property to a smaller value.

**Closed by jheer** 2016-12-22 18:32 UTC
Labels: bug
